"""The lock files under requirements/ are written by one tool: the one whose
command each of them records.

Dependabot updated those files twice by moving pins one at a time, and both
times the result could not be installed: wrapt past the ceiling python-can
sets, then pylink-square past the one pyocd sets, the second time with the
markers that carry Windows and macOS packages dropped as well. Every
hash-pinned install in the matrix failed with ResolutionImpossible, and the
locks had to be regenerated by hand with the commands on their second lines.

What is pinned here is that the tool that replaced that reads those commands
and nothing else, that its refresh moves exact pins in the inputs and then
recompiles with --upgrade, that its check recompiles without --upgrade and
leaves the tree as it found it while naming the pins that moved, that the
workflows install uv by hash and pin every action by commit, that the weekly
refresh starts the checks its pull request would otherwise never get, and that
Dependabot no longer has a pip entry to do it the wrong way with.
"""

from __future__ import annotations

import ast
import re
import shlex
import sys
from pathlib import Path

import pytest
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tools"))

from refresh_locks import (  # noqa: E402
    Change,
    LockError,
    bump_exact_pins,
    check,
    input_of,
    main,
    pins,
    recorded_command,
    refresh,
    summary,
    uv_requirement,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CI_WORKFLOW = REPOSITORY_ROOT / ".github" / "workflows" / "ci.yml"
REFRESH_WORKFLOW = REPOSITORY_ROOT / ".github" / "workflows" / "lock-refresh.yml"
REVIEW_WORKFLOW = REPOSITORY_ROOT / ".github" / "workflows" / "dependency-review.yml"
DEPENDABOT = REPOSITORY_ROOT / ".github" / "dependabot.yml"
PINNED_ACTION = re.compile(r"^[\w.-]+/[\w./-]+@[0-9a-f]{40}$")

HEADER = "# This file was autogenerated by uv via the following command:\n"
UV_HASHES = (
    "uv==0.12.9 \\\n"
    "    --hash=sha256:00ff9f34c04055ebc3e1599ee459f5ae0d42c17cd6a1d8d029f0389e64a1419c \\\n"
    "    --hash=sha256:0a4c3f6f1d5b0a1f0b6f4b1a7c2d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d\n"
    "    # via -r requirements/container.in\n"
)


def lock(command: str, body: str) -> str:
    return f"{HEADER}#    {command}\n{body}"


def put(path: Path, text: str) -> None:
    """Write the text byte for byte; the line endings are part of what is tested."""
    path.write_bytes(text.encode("utf-8"))


def write_tree(root: Path, *, container_in: str = "uv==0.12.9\npyocd==0.45.1\nsetuptools>=77\nwheel\n") -> None:
    """A repository shaped like this one: two inputs, two locks, one pyproject."""
    requirements = root / "requirements"
    requirements.mkdir()
    put(root / "pyproject.toml", "[project]\nname = 'x'\nversion = '0'\n")
    put(requirements / "container.in", container_in)
    put(
        requirements / "container.txt",
        lock(
            "uv pip compile --generate-hashes --universal --python-version 3.12 requirements/container.in -o requirements/container.txt",
            "pyocd==0.45.1 \\\n    --hash=sha256:aa\n    # via -r requirements/container.in\n" + UV_HASHES,
        ),
    )
    put(requirements / "runtime.in", 'pyserial>=3.5\ntomli>=2; python_version < "3.11"\n')
    put(
        requirements / "runtime.txt",
        lock(
            "uv pip compile --generate-hashes --universal --python-version 3.10 requirements/runtime.in -o requirements/runtime.txt",
            "pyserial==3.5 \\\n    --hash=sha256:bb\n    # via -r requirements/runtime.in\n"
            "tomli==2.4.1 ; python_full_version < '3.11' \\\n    --hash=sha256:cc\n    # via -r requirements/runtime.in\n",
        ),
    )


class FakeUv:
    """Records every command and plays the resolver: rewrites the lock named by -o."""

    def __init__(self, root: Path, newest: dict[str, str] | None = None, rewrite: dict[str, str] | None = None) -> None:
        self.root = root
        self.newest = newest or {}
        self.rewrite = rewrite or {}
        self.calls: list[tuple[list[str], str | None, Path]] = []

    def __call__(self, command: list[str], stdin: str | None, cwd: Path) -> str:
        self.calls.append((list(command), stdin, cwd))
        assert command[:3] == ["uv", "pip", "compile"]
        if command[-1] == "-":
            assert stdin is not None
            return "".join(f"{name}=={self.newest[name]}\n" for name in stdin.split() if name in self.newest)
        output = command[command.index("-o") + 1]
        if output in self.rewrite:
            put(cwd / output, self.rewrite[output])
        return ""


def test_the_tool_runs_on_every_python_this_project_supports_with_nothing_installed() -> None:
    """The CI job installs uv and nothing else before running it, on 3.10 too."""
    source = (REPOSITORY_ROOT / "tools" / "refresh_locks.py").read_text(encoding="utf-8")
    modules = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.Import):
            modules.update(alias.name.split(".")[0] for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            modules.add(node.module.split(".")[0])

    assert "tomllib" not in modules
    assert modules <= set(sys.stdlib_module_names), modules - set(sys.stdlib_module_names)


def test_the_recorded_command_is_read_off_the_locks_second_line(tmp_path: Path) -> None:
    write_tree(tmp_path)

    command = recorded_command(tmp_path, tmp_path / "requirements" / "container.txt")

    assert command == shlex.split(
        "uv pip compile --generate-hashes --universal --python-version 3.12 requirements/container.in -o requirements/container.txt"
    )
    assert input_of(command) == "requirements/container.in"


@pytest.mark.parametrize(
    ("head", "reason"),
    [
        ("# autogenerated by pip-compile\n#    pip-compile requirements/container.in\n", "does not start with the uv header"),
        (HEADER + "#    pip-compile requirements/container.in -o requirements/container.txt\n", "not a uv pip compile command"),
        (HEADER + "#    uv pip compile requirements/container.in -o requirements/other.txt\n", "not itself"),
    ],
)
def test_a_lock_whose_header_is_not_the_command_that_wrote_it_is_refused(tmp_path: Path, head: str, reason: str) -> None:
    """A file another tool rewrote has lost the one line this tool works from."""
    write_tree(tmp_path)
    path = tmp_path / "requirements" / "container.txt"
    put(path, head + UV_HASHES)

    with pytest.raises(LockError, match=reason):
        recorded_command(tmp_path, path)


def test_a_command_compiling_two_inputs_is_refused() -> None:
    command = shlex.split("uv pip compile --universal a.in b.in -o requirements/x.txt")

    with pytest.raises(LockError, match="compiles 2 inputs"):
        input_of(command)


def test_pins_are_read_by_canonical_name_up_to_the_hash_continuation() -> None:
    text = "Pylink_Square==1.7.0 \\\n    --hash=sha256:aa\ntomli==2.4.1 ; python_full_version < '3.11' \\\n    # via x\n"

    assert pins(text) == {"pylink-square": "1.7.0", "tomli": "2.4.1"}


def test_a_refresh_moves_the_exact_pins_and_leaves_the_floors(tmp_path: Path) -> None:
    """`uv==` moves; `setuptools>=77`, `wheel` and the tomli floor stay where the maintainer put them."""
    write_tree(tmp_path)
    uv = FakeUv(tmp_path, newest={"uv": "0.12.15", "pyocd": "0.45.1"})

    changes = bump_exact_pins(tmp_path, uv)

    assert changes == [Change("requirements/container.in", "uv", "0.12.9", "0.12.15")]
    assert (tmp_path / "requirements" / "container.in").read_text(encoding="utf-8") == "uv==0.12.15\npyocd==0.45.1\nsetuptools>=77\nwheel\n"
    assert (tmp_path / "requirements" / "runtime.in").read_text(encoding="utf-8") == 'pyserial>=3.5\ntomli>=2; python_version < "3.11"\n'
    # The newest release is asked of uv, for the interpreter the lock names.
    lookups = [call for call in uv.calls if call[0][-1] == "-"]
    assert len(lookups) == 1
    assert "--no-deps" in lookups[0][0]
    assert lookups[0][0][lookups[0][0].index("--python-version") + 1] == "3.12"
    assert lookups[0][1] == "pyocd\nuv\n"


def test_an_exact_pin_keeps_its_line_ending(tmp_path: Path) -> None:
    write_tree(tmp_path, container_in="uv==0.12.9\r\npyocd==0.45.1\r\n")

    bump_exact_pins(tmp_path, FakeUv(tmp_path, newest={"uv": "0.12.15", "pyocd": "0.45.1"}))

    assert (tmp_path / "requirements" / "container.in").read_bytes() == b"uv==0.12.15\r\npyocd==0.45.1\r\n"


def test_a_refresh_recompiles_every_lock_with_its_own_command_and_upgrade(tmp_path: Path) -> None:
    write_tree(tmp_path)
    rewritten = lock(
        "uv pip compile --generate-hashes --universal --python-version 3.10 requirements/runtime.in -o requirements/runtime.txt",
        "pyserial==3.6 \\\n    --hash=sha256:dd\n    # via -r requirements/runtime.in\n",
    )
    uv = FakeUv(tmp_path, newest={"uv": "0.12.9", "pyocd": "0.45.1"}, rewrite={"requirements/runtime.txt": rewritten})

    changes = refresh(tmp_path, uv)

    compiles = [call for call in uv.calls if call[0][-1] != "-"]
    assert [call[0][-1] for call in compiles] == ["--upgrade", "--upgrade"]
    assert [call[0][call[0].index("-o") + 1] for call in compiles] == ["requirements/container.txt", "requirements/runtime.txt"]
    # From the repository root, where the recorded paths resolve.
    assert {call[2] for call in uv.calls} == {tmp_path}
    assert changes == [
        Change("requirements/runtime.txt", "pyserial", "3.5", "3.6"),
        Change("requirements/runtime.txt", "tomli", "2.4.1", None),
    ]


def test_the_check_recompiles_without_upgrade_and_leaves_the_tree_as_found(tmp_path: Path) -> None:
    """A lock that no longer follows from its input is named with the pins that move."""
    write_tree(tmp_path)
    path = tmp_path / "requirements" / "runtime.txt"
    original = path.read_bytes()
    rewritten = lock(
        "uv pip compile --generate-hashes --universal --python-version 3.10 requirements/runtime.in -o requirements/runtime.txt",
        "pyserial==3.4 \\\n    --hash=sha256:ee\n    # via -r requirements/runtime.in\n"
        "tomli==2.4.1 ; python_full_version < '3.11' \\\n    --hash=sha256:cc\n    # via -r requirements/runtime.in\n",
    )
    uv = FakeUv(tmp_path, rewrite={"requirements/runtime.txt": rewritten})

    problems = check(tmp_path, uv)

    assert problems == [
        "requirements/runtime.txt does not follow from its input: recompiling it moves pyserial 3.5 to 3.4",
        "Regenerate with the command on the lock's second line, or refresh every lock with: python tools/refresh_locks.py",
    ]
    assert path.read_bytes() == original
    assert all("--upgrade" not in call[0] for call in uv.calls)
    assert all(call[0][-1] != "-" for call in uv.calls), "a check asks the index for nothing new"


def test_a_lock_that_recompiles_to_itself_passes_the_check(tmp_path: Path) -> None:
    write_tree(tmp_path)

    assert check(tmp_path, FakeUv(tmp_path)) == []


def test_the_check_restores_the_lock_when_uv_refuses(tmp_path: Path) -> None:
    write_tree(tmp_path)
    path = tmp_path / "requirements" / "container.txt"
    original = path.read_bytes()

    def refusing(command: list[str], stdin: str | None, cwd: Path) -> str:
        put(cwd / "requirements" / "container.txt", "half written")
        raise LockError("uv pip compile failed with exit status 1:\nerror: no solution found")

    with pytest.raises(LockError, match="no solution found"):
        check(tmp_path, refusing)
    assert path.read_bytes() == original


def test_the_summary_is_one_table_by_file_and_name() -> None:
    text = summary(
        [
            Change("requirements/dev.txt", "ruff", "0.16.5", "0.16.7"),
            Change("requirements/container.in", "uv", "0.12.9", "0.12.15"),
            Change("requirements/dev.txt", "hidapi", None, "0.15.0"),
        ]
    )

    assert text.splitlines()[-4:] == [
        "| --- | --- | --- | --- |",
        "| uv | requirements/container.in | 0.12.9 | 0.12.15 |",
        "| hidapi | requirements/dev.txt | absent | 0.15.0 |",
        "| ruff | requirements/dev.txt | 0.16.5 | 0.16.7 |",
    ]
    assert summary([]) == "Every lock was already current.\n"


def test_uv_is_printed_with_its_hashes_and_nothing_else(tmp_path: Path) -> None:
    write_tree(tmp_path)

    text = uv_requirement(tmp_path)

    assert text.startswith("uv==0.12.9 \\\n")
    assert text.count("--hash=sha256:") == 2
    assert "pyocd" not in text
    assert "# via" not in text


@pytest.mark.parametrize(
    ("body", "reason"),
    [("pyocd==0.45.1 \\\n    --hash=sha256:aa\n", "pins no uv"), ("uv==0.12.9\n", "without a hash")],
)
def test_a_container_lock_that_cannot_pin_uv_is_refused(tmp_path: Path, body: str, reason: str) -> None:
    write_tree(tmp_path)
    put(tmp_path / "requirements" / "container.txt", lock("uv pip compile x -o requirements/container.txt", body))

    with pytest.raises(LockError, match=reason):
        uv_requirement(tmp_path)


def test_main_reports_the_check_on_stderr_and_exit_status(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    write_tree(tmp_path)
    rewritten = lock(
        "uv pip compile --generate-hashes --universal --python-version 3.12 requirements/container.in -o requirements/container.txt",
        "pyocd==0.46.0 \\\n    --hash=sha256:ff\n" + UV_HASHES,
    )

    assert main(["--check", "--root", str(tmp_path)], run=FakeUv(tmp_path)) == 0
    assert main(["--check", "--root", str(tmp_path)], run=FakeUv(tmp_path, rewrite={"requirements/container.txt": rewritten})) == 1
    assert "recompiling it moves pyocd 0.45.1 to 0.46.0" in capsys.readouterr().err


def test_main_writes_the_summary_the_pull_request_carries(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    write_tree(tmp_path)
    summary_path = tmp_path / "summary.md"

    status = main(["--summary", str(summary_path), "--root", str(tmp_path)], run=FakeUv(tmp_path, newest={"uv": "0.12.15", "pyocd": "0.45.1"}))

    assert status == 0
    assert "| uv | requirements/container.in | 0.12.9 | 0.12.15 |" in summary_path.read_text(encoding="utf-8")
    assert capsys.readouterr().out == summary_path.read_text(encoding="utf-8")


def test_main_refuses_a_lock_it_cannot_read_by_name(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    write_tree(tmp_path)
    (tmp_path / "requirements" / "runtime.txt").write_text("pyserial==3.5\n", encoding="utf-8")

    assert main(["--check", "--root", str(tmp_path)], run=FakeUv(tmp_path)) == 1
    assert "requirements/runtime.txt does not start with the uv header" in capsys.readouterr().err


def test_every_lock_in_this_repository_records_a_command_that_writes_it() -> None:
    """The tool has one lock it cannot read, and the refresh stops at it."""
    requirements = REPOSITORY_ROOT / "requirements"
    if not requirements.is_dir():
        pytest.skip("requirements/ is repository content and this checkout has none")
    for path in sorted(requirements.glob("*.txt")):
        command = recorded_command(REPOSITORY_ROOT, path)
        source = input_of(command)
        assert (REPOSITORY_ROOT / source).is_file(), f"{path.name} compiles {source}, which is not here"
        assert "--universal" in command and "--generate-hashes" in command, path.name


# The workflows.


def workflow_document(path: Path) -> dict:
    if not path.is_file():
        pytest.skip(f"{path.name} is repository content and this checkout has none")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def triggers(workflow: dict) -> dict:
    return workflow.get("on", workflow.get(True, {}))


def run_lines(job: dict) -> list[str]:
    lines = []
    for step in job.get("steps", []):
        for raw in step.get("run", "").splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                lines.append(line)
    return lines


def refresh_job() -> dict:
    return workflow_document(REFRESH_WORKFLOW)["jobs"]["refresh"]


def test_dependabot_has_no_pip_entry_left_to_rewrite_the_locks_with() -> None:
    configuration = workflow_document(DEPENDABOT)

    assert [entry["package-ecosystem"] for entry in configuration["updates"]] == ["docker", "docker", "github-actions"]


def test_the_refresh_runs_on_a_schedule_and_on_request_and_on_nothing_else() -> None:
    assert set(triggers(workflow_document(REFRESH_WORKFLOW))) == {"workflow_dispatch", "schedule"}


def test_the_refresh_pins_every_action_by_commit() -> None:
    for workflow in (REFRESH_WORKFLOW, CI_WORKFLOW, REVIEW_WORKFLOW):
        for job in workflow_document(workflow)["jobs"].values():
            for step in job.get("steps", []):
                used = step.get("uses")
                assert used is None or PINNED_ACTION.match(used), f"{workflow.name} uses {used}"


def test_every_install_in_the_refresh_and_the_check_requires_hashes() -> None:
    """uv itself arrives by the hashes the container lock carries for it."""
    jobs = [refresh_job(), workflow_document(CI_WORKFLOW)["jobs"]["lock_consistency"]]
    for job in jobs:
        lines = run_lines(job)
        installs = [line for line in lines if "pip install" in line]
        assert installs, lines
        assert all("--require-hashes" in line for line in installs), installs
        assert any("refresh_locks.py --uv-requirement" in line for line in lines), lines


def test_the_refresh_runs_the_tool_and_hands_its_summary_to_the_pull_request() -> None:
    lines = run_lines(refresh_job())

    assert "python tools/refresh_locks.py --summary lock-refresh-summary.md" in lines
    assert any("gh pr create" in line and "--body-file lock-refresh-summary.md" in line for line in lines), lines
    assert any(line.startswith("git push --force origin") for line in lines), lines


def test_the_refresh_starts_the_checks_its_pull_request_never_gets_on_its_own() -> None:
    """A pull request opened with the workflow token starts no workflow.

    workflow_dispatch is the documented exception, so the refresh starts the
    required workflow and the dependency review on its branch by hand, and both
    have to be startable that way.
    """
    lines = run_lines(refresh_job())

    assert any(line.startswith("gh workflow run ci.yml --ref") for line in lines), lines
    assert any(line.startswith("gh workflow run dependency-review.yml --ref") for line in lines), lines
    assert "workflow_dispatch" in triggers(workflow_document(CI_WORKFLOW))
    assert "workflow_dispatch" in triggers(workflow_document(REVIEW_WORKFLOW))
    assert refresh_job()["permissions"]["actions"] == "write"


def test_the_dependency_review_compares_the_branch_with_master_when_started_by_hand() -> None:
    steps = workflow_document(REVIEW_WORKFLOW)["jobs"]["dependency-review"]["steps"]
    review = [step for step in steps if "dependency-review-action" in step.get("uses", "")]

    assert len(review) == 1
    assert "workflow_dispatch" in review[0]["with"]["base-ref"] and "'master'" in review[0]["with"]["base-ref"]
    assert "github.ref_name" in review[0]["with"]["head-ref"]


def test_the_lock_check_is_one_of_the_jobs_the_required_check_reads() -> None:
    workflow = workflow_document(CI_WORKFLOW)
    required = workflow["jobs"]["required-ci"]

    assert "lock_consistency" in required["needs"]
    assert "needs.lock_consistency.result" in required["steps"][0]["run"]
    assert "python tools/refresh_locks.py --check" in run_lines(workflow["jobs"]["lock_consistency"])
