"""Carrying an attached board into a configuration that was written without it.

hardci-hq#76: `setup` ran with nothing plugged in, so `init` wrote placeholders,
and after plugging the board in there was no way back into the file. The agent
stopped correctly and printed a 24-character probe serial for a person to retype.

The four things the issue asks to be true are one test each, and they are the
first four here:

* a placeholder configuration can be completed without hand transcription,
* permissions do not move while that happens,
* a value a person set is never replaced,
* and the whole sequence — `setup` without a board, plug in, green `doctor` —
  runs with nobody editing YAML.

The rest is what "unset" means precisely, what happens when discovery finds more
than one board or none, and what happens when it contradicts the file. Every one
of those has to have an answer a caller can act on; a silent choice among them is
the failure mode that would make this path worse than the retyping.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import pytest
import yaml
from conftest import FAKE_STLINK, write_authoritative_config

from agentic_hil.adopt import PROJECT_CONFIG_ADOPT, is_unset, plan_adoption, project_config_adopt_hardware
from agentic_hil.cli import adopt_hardware, doctor, init_config
from agentic_hil.config import DEFAULT_CONFIG_TEMPLATE, load_authoritative_config
from agentic_hil.configwrite import ACTOR_HUMAN, PROJECT_CONFIG_SET
from agentic_hil.knowledge import CONFIG_DESCRIPTION_RIGHT, CONFIG_PERMISSIONS_RIGHT, CONFIG_WRITE_RIGHT
from agentic_hil.tools import AgenticHILToolService

PROBE_SERIAL = "0045002B3038510934333935"
PROVENANCE = {"created_by": "agent", "created_via": "mcp:project_config_create", "created_at": "2026-01-01T00:00:00Z", "agentic_hil_version": "0.0.0"}


def attached(monkeypatch: pytest.MonkeyPatch, **overrides: Any) -> dict:
    """Stand in for bootstrap discovery: one ST-Link, one target, one COM port."""
    discovery: dict[str, Any] = {
        "ok": True,
        "tool": "bootstrap_hardware_discovery",
        "backend": "stlink",
        "executable": FAKE_STLINK.as_posix(),
        "probe_id": PROBE_SERIAL,
        "target": {"probe_id": PROBE_SERIAL, "controller": "STM32F446RE"},
        "com_port": {"device": "COM9", "serial_number": PROBE_SERIAL},
        "available_com_ports": {"ok": True, "ports": [{"device": "COM9", "serial_number": PROBE_SERIAL}]},
        "side_effect_committed": False,
        "side_effect_status": "not_started",
        "hardware_state": "unchanged",
        "cleanup_required": False,
        "summary": "One attached STM32 target was identified through ST-Link HOTPLUG discovery.",
    }
    discovery.update(overrides)
    seen: dict[str, Any] = {}

    def discover(timeout_s: float = 10.0, *, probe_id: str | None = None) -> dict:
        seen["probe_id"] = probe_id
        return discovery

    monkeypatch.setattr("agentic_hil.adopt.discover_attached_hardware", discover)
    discovery["_selected"] = seen
    return discovery


def placeholder_bench(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, **grants: bool) -> tuple[Path, Path]:
    """The file `init` writes when nothing was attached: type stlink, all null.

    `type` is the one identity field this path cannot set, because it decides
    which program reaches the board rather than what the board is. A bench that
    means to be driven through ST-Link says so; everything else in the entry is
    still the placeholder `init` wrote."""
    workspace = (tmp_path / "workspace").resolve()
    path = write_authoritative_config(
        workspace,
        monkeypatch,
        config_root=Path(os.environ["APPDATA"]) / "config-adopt",
        config_version=2,
        permissions={},
        debugger_type="stlink",
    )
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    document["target"] = {"name": "example-target", "controller": "unknown-controller"}
    document["debuggers"]["dut"].update({"probe_id": None, "executable": None})
    document["com_ports"] = {}
    document["provenance"] = dict(PROVENANCE)
    document["permissions"] = {CONFIG_WRITE_RIGHT: False, CONFIG_DESCRIPTION_RIGHT: False, CONFIG_PERMISSIONS_RIGHT: False, **grants}
    path.write_text("# Generated by Agentic HIL; every permission below is false.\n" + yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    monkeypatch.chdir(workspace)
    return workspace, path


def service(workspace: Path) -> AgenticHILToolService:
    return AgenticHILToolService(load_authoritative_config(workspace), frontend="mcp")


def document_of(path: Path) -> dict:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(loaded, dict)
    return loaded


def granted(node: object, prefix: str = "") -> dict[str, Any]:
    """Every permission in a document, by dotted path, whatever it is called."""
    found: dict[str, Any] = {}
    if isinstance(node, dict):
        for key, value in node.items():
            path = f"{prefix}.{key}" if prefix else str(key)
            if str(key).startswith("allow_"):
                found[path] = value
            elif str(key) == "permissions" and isinstance(value, dict):
                found.update({f"{path}.{flag}": state for flag, state in value.items()})
            found.update(granted(value, path))
    return found


# ---------------------------------------------------------------------------
# The four boxes hardci-hq#76 asks to be ticked.


def test_a_placeholder_configuration_is_completed_without_transcription(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The first box: the values land in the file, and nobody types them.

    The call carries no value of its own — every one of the four keys below comes
    out of discovery, and the tool's whole argument surface is booleans and
    names."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    attached(monkeypatch)
    tools = service(workspace)
    try:
        planned = tools.call(PROJECT_CONFIG_ADOPT)
        assert planned["ok"] is True, planned
        assert planned["applied"] is False, "reading hardware must not write by itself"
        assert sorted(item["key"] for item in planned["carried"]) == [
            "com_ports.dut_uart.device",
            "debuggers.dut.executable",
            "debuggers.dut.probe_id",
            "target.controller",
        ]
        assert document_of(path)["debuggers"]["dut"]["probe_id"] is None

        applied = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
        assert applied["ok"] is True, applied
        assert applied["applied"] is True
    finally:
        tools.close()

    document = document_of(path)
    assert document["debuggers"]["dut"]["probe_id"] == PROBE_SERIAL
    assert document["debuggers"]["dut"]["executable"] == FAKE_STLINK.as_posix()
    assert document["target"]["controller"] == "stm32f446re"
    assert document["com_ports"]["dut_uart"]["device"] == "COM9"
    # One write path, so one provenance record: the same one project_config_set
    # writes, naming the call that actually moved the keys.
    assert document["provenance"]["last_modified_via"] == f"mcp:{PROJECT_CONFIG_ADOPT}"
    assert document["provenance"]["last_modified_by"] == "agent"
    assert document["provenance"]["modification_count"] == 1
    assert document["provenance"]["created_at"] == PROVENANCE["created_at"], "a change does not answer who wrote the file"


def test_permissions_do_not_move_while_the_hardware_is_carried_in(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The second box, checked against the document rather than against the call.

    Every permission in the file is collected before and after, by walking what
    is actually there — including the COM port entry this call brings into
    existence, which arrives with its permissions written by the server."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True, CONFIG_PERMISSIONS_RIGHT: True})
    attached(monkeypatch)
    before = granted(document_of(path))
    tools = service(workspace)
    try:
        applied = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert applied["ok"] is True, applied
    assert applied["permissions_changed"] == []
    after = granted(document_of(path))
    assert not [key for key in set(before) | set(after) if before.get(key, False) != after.get(key, False)]
    # The port that did not exist before now does, and it may be read and not
    # written — the permission block came from the server, not from this call.
    assert after["com_ports.dut_uart.permissions.allow_write"] is False
    assert applied["created_entries"] == ["com_ports.dut_uart"]
    # Even with the permissions grant open, which is the state that could have
    # let something through: nothing in this path can name a permission key.
    assert all(not str(item["key"]).startswith("permissions") and ".permissions." not in str(item["key"]) for item in applied["carried"])


def test_a_value_a_person_set_is_reported_and_never_replaced(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The third box, and the one that decides whether this path is safe at all.

    A configuration that names another probe is a bench somebody set up, maybe
    for a second board that is not plugged in right now. Overwriting it because
    something else is attached would be the worst thing this could do."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    document = document_of(path)
    document["debuggers"]["dut"]["probe_id"] = "066AFF495451885087171450"
    document["target"]["controller"] = "stm32f411re"
    path.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    attached(monkeypatch)

    tools = service(workspace)
    try:
        applied = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert applied["ok"] is True, applied
    kept = {item["key"]: item for item in applied["kept"]}
    assert sorted(kept) == ["debuggers.dut.probe_id", "target.controller"]
    assert kept["debuggers.dut.probe_id"]["configured_value"] == "066AFF495451885087171450"
    assert kept["debuggers.dut.probe_id"]["discovered_value"] == PROBE_SERIAL
    after = document_of(path)
    assert after["debuggers"]["dut"]["probe_id"] == "066AFF495451885087171450"
    assert after["target"]["controller"] == "stm32f411re"
    # The disagreement is named in what the caller is told to do next, so it
    # cannot be read as "everything is fine now".
    assert any("kept" in step for step in applied["next_steps"])


def test_setup_without_a_board_then_plugging_it_in_reaches_a_green_doctor(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The fourth box, end to end, with nobody editing YAML.

    `init` runs with nothing attached and writes the placeholder skeleton. The
    board arrives. `agentic-hil adopt-hardware` carries it in — as the operator,
    which is the authority `init` itself runs under, so no grant has to be edited
    into a file to make the command that fills the file work. Then `doctor` reads
    a configuration that names the probe.
    """
    workspace = (tmp_path / "workspace").resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    config_root = Path(os.environ["APPDATA"]) / "config-adopt-end-to-end"
    monkeypatch.setenv("APPDATA", str(config_root))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(config_root))
    monkeypatch.chdir(workspace)

    # No profile in the workspace and nothing attached: exactly what `setup`
    # does on a bench whose board is still in its box.
    monkeypatch.setattr("agentic_hil.cli.discover_attached_hardware", lambda *args, **kwargs: {"ok": False, "error_type": "adapter_not_found", "summary": "No ST-Link probe is attached."})
    started = init_config()
    assert started["ok"] is True, started
    path = Path(started["path"])
    placeholder = document_of(path)
    assert placeholder["debuggers"]["dut"]["probe_id"] is None
    assert placeholder["target"]["controller"] == "unknown-controller"

    # The operator plugs the board in. The skeleton's backend is OpenOCD, so the
    # one field that belongs to a backend rather than to a board has to be told
    # which backend this bench is; everything else follows from the hardware.
    switched = document_of(path)
    switched["debuggers"]["dut"]["type"] = "stlink"
    path.write_text(yaml.safe_dump(switched, sort_keys=False), encoding="utf-8")
    attached(monkeypatch)

    carried = adopt_hardware()
    assert carried["ok"] is True, carried
    assert carried["applied"] is True
    assert {item["key"] for item in carried["carried"]} == {
        "debuggers.dut.probe_id",
        "debuggers.dut.executable",
        "target.controller",
        "com_ports.dut_uart.device",
    }
    filled = document_of(path)
    assert filled["debuggers"]["dut"]["probe_id"] == PROBE_SERIAL
    assert filled["provenance"]["last_modified_by"] == ACTOR_HUMAN
    assert filled["provenance"]["last_modified_via"] == "cli:adopt-hardware"
    # No grant was needed and none appeared. The skeleton names no project
    # permissions at all, and it still names none.
    assert CONFIG_DESCRIPTION_RIGHT not in (filled.get("permissions") or {})

    checked = doctor()
    assert checked["ok"] is True, checked
    assert checked["debuggers"]["dut"]["probe_id"] == PROBE_SERIAL
    assert checked["target"]["controller"] == "stm32f446re"
    assert checked["com_ports"]["dut_uart"]["device"] == "COM9"
    # Green, and honestly so: the skeleton grants nothing, so the debugger check
    # is skipped rather than passed. That is the state the session behind #76 was
    # in — the complaint was not that the check failed but that the file held
    # placeholders and nothing could fill them.
    assert checked["debugger"]["skipped"] is True

    # And once the operator grants what this bench is for — the one edit that is
    # theirs to make and that no path here can make for them — the check really
    # runs, against the probe this command entered.
    opened = document_of(path)
    opened["debuggers"]["dut"]["permissions"]["allow_reset"] = True
    path.write_text(yaml.safe_dump(opened, sort_keys=False), encoding="utf-8")
    exercised = doctor()
    assert exercised["ok"] is True, exercised
    assert exercised["debuggers"]["dut"]["check"]["ok"] is True
    assert exercised["debuggers"]["dut"]["check"]["backend"] == "stlink"


# ---------------------------------------------------------------------------
# What "unset" means, precisely.


def test_unset_is_absent_null_empty_or_the_shipped_placeholder() -> None:
    """The definition, against the skeleton that actually writes the placeholders.

    Read out of `DEFAULT_CONFIG_TEMPLATE` rather than listed, so a template that
    changes its placeholder cannot leave this check recognising the old one."""
    skeleton = yaml.safe_load(DEFAULT_CONFIG_TEMPLATE)
    assert is_unset(None, "target", "controller")
    assert is_unset("", "target", "controller")
    assert is_unset("   ", "target", "controller")
    assert is_unset(skeleton["target"]["controller"], "target", "controller")
    assert is_unset(skeleton["debuggers"]["dut"]["probe_id"], "debuggers", "probe_id")
    # And everything else is a value somebody chose, including one that is wrong.
    assert not is_unset("stm32f446re", "target", "controller")
    assert not is_unset("unknown-controller-2", "target", "controller")
    assert not is_unset(PROBE_SERIAL, "debuggers", "probe_id")
    assert not is_unset("COM4", "com_ports", "device")


def test_a_value_that_already_matches_the_hardware_is_not_written_again(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Running this twice changes nothing the second time.

    An idempotent second call matters because the obvious operator reflex after
    plugging a second board in is to run it again."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    attached(monkeypatch)
    tools = service(workspace)
    try:
        first = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
        assert first["ok"] is True, first
        before = path.read_text(encoding="utf-8")
        second = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert second["ok"] is True, second
    assert second["applied"] is False
    assert second["carried"] == []
    assert sorted(item["key"] for item in second["already_current"]) == [
        "com_ports.dut_uart.device",
        "debuggers.dut.executable",
        "debuggers.dut.probe_id",
        "target.controller",
    ]
    assert path.read_text(encoding="utf-8") == before
    assert document_of(path)["provenance"]["modification_count"] == 1


# ---------------------------------------------------------------------------
# More than one candidate, and none at all.


def test_two_attached_probes_are_named_rather_than_chosen(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Discovery refuses to pick a board, and says how to pick one."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    attached(
        monkeypatch,
        ok=False,
        error_type="ambiguous_hardware",
        summary="More than one ST-Link probe is attached; discovery will not choose a board.",
        probes=[{"probe_id": PROBE_SERIAL}, {"probe_id": "066AFF495451885087171450"}],
        next_step="Ask which board this is about and name its serial as probe_id; every attached serial is listed under `probes`.",
    )
    tools = service(workspace)
    try:
        refused = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert refused["ok"] is False
    assert refused["error_type"] == "ambiguous_hardware"
    assert [entry["probe_id"] for entry in refused["probes"]] == [PROBE_SERIAL, "066AFF495451885087171450"]
    assert "probe_id" in refused["next_step"]
    assert document_of(path)["debuggers"]["dut"]["probe_id"] is None


def test_the_named_probe_reaches_discovery_and_selects_among_what_is_attached(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    workspace, _ = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    discovery = attached(monkeypatch)
    tools = service(workspace)
    try:
        planned = tools.call(PROJECT_CONFIG_ADOPT, {"probe_id": PROBE_SERIAL})
    finally:
        tools.close()
    assert planned["ok"] is True, planned
    assert discovery["_selected"]["probe_id"] == PROBE_SERIAL


def test_two_configured_debuggers_and_no_name_is_refused(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The mirror case: several entries in the file, and no way to know which."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    document = document_of(path)
    # A distinct resource_id, because two entries that name no probe and nothing
    # else to tell them apart are one physical unit twice and refused at load.
    document["debuggers"]["spare"] = {**document["debuggers"]["dut"], "probe_id": None, "resource_id": "spare-board"}
    path.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    attached(monkeypatch)

    tools = service(workspace)
    try:
        refused = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
        assert refused["ok"] is False
        assert refused["error_type"] == "invalid_argument"
        assert refused["field"] == "debugger_id"
        assert refused["configured_debuggers"] == ["dut", "spare"]

        chosen = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True, "debugger_id": "spare"})
    finally:
        tools.close()

    assert chosen["ok"] is True, chosen
    after = document_of(path)
    assert after["debuggers"]["spare"]["probe_id"] == PROBE_SERIAL
    assert after["debuggers"]["dut"]["probe_id"] is None


def test_nothing_attached_is_an_answer_and_not_a_written_file(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    before = path.read_text(encoding="utf-8")
    attached(monkeypatch, ok=False, error_type="adapter_not_found", summary="No ST-Link probe is attached.")
    tools = service(workspace)
    try:
        refused = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert refused["ok"] is False
    assert refused["error_type"] == "adapter_not_found"
    assert refused["side_effect_committed"] is False
    assert path.read_text(encoding="utf-8") == before


def test_a_probe_without_its_own_com_port_says_so_instead_of_guessing(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """No serial-number match means no answer, and the host ports come back.

    A board wired to a separate USB-serial adapter has no port that carries the
    probe's serial. Picking the only host port that happens to be there is how a
    configuration ends up talking to somebody else's device."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    attached(monkeypatch, com_port=None, available_com_ports={"ok": True, "ports": [{"device": "COM4", "serial_number": "SOMETHINGELSE"}]})
    tools = service(workspace)
    try:
        applied = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert applied["ok"] is True, applied
    unavailable = {item["key"]: item for item in applied["unavailable"]}
    assert "com_ports.<name>.device" in unavailable
    assert unavailable["com_ports.<name>.device"]["host_com_ports"] == [{"device": "COM4", "serial_number": "SOMETHINGELSE"}]
    assert document_of(path)["com_ports"] == {}
    # The three keys that could be answered still were.
    assert sorted(item["key"] for item in applied["carried"]) == ["debuggers.dut.executable", "debuggers.dut.probe_id", "target.controller"]


def test_several_com_ports_and_no_name_is_not_resolved_silently(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    document = document_of(path)
    document["com_ports"] = {
        "dut_uart": {"device": "COM3", "baudrate": 115200, "permissions": {"allow_write": False}},
        "bootloader": {"device": "COM4", "baudrate": 115200, "permissions": {"allow_write": False}},
    }
    path.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    attached(monkeypatch)

    tools = service(workspace)
    try:
        applied = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
        assert applied["ok"] is True, applied
        assert applied["com_port_id"] is None
        unavailable = {item["key"]: item for item in applied["unavailable"]}
        assert unavailable["com_ports.<name>.device"]["configured_com_ports"] == ["bootloader", "dut_uart"]
        assert document_of(path)["com_ports"]["dut_uart"]["device"] == "COM3"

        # Naming one of them does not make it overwritable: a configured port
        # always has a device, and a device somebody wrote is not a placeholder.
        existing = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True, "com_port_id": "bootloader"})
        assert existing["ok"] is True, existing
        assert {item["key"] for item in existing["kept"]} == {"com_ports.bootloader.device"}
        assert document_of(path)["com_ports"]["bootloader"]["device"] == "COM4"

        # Naming an entry that does not exist yet is how the probe's own port
        # gets one, and the server writes its permissions.
        named = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True, "com_port_id": "probe_uart"})
    finally:
        tools.close()

    assert named["ok"] is True, named
    after = document_of(path)
    assert after["com_ports"]["probe_uart"]["device"] == "COM9"
    assert after["com_ports"]["probe_uart"]["permissions"] == {"allow_write": False}


# ---------------------------------------------------------------------------
# The backend the executable belongs to.


def test_a_toolchain_from_another_backend_is_reported_and_not_written(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """An OpenOCD entry does not take an STM32CubeProgrammer path.

    It would load and then fail at the first call, and `type` is deliberately not
    a key this door opens: it decides which program reaches the board."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    document = document_of(path)
    document["debuggers"]["dut"]["type"] = "openocd"
    path.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")
    attached(monkeypatch)

    tools = service(workspace)
    try:
        applied = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert applied["ok"] is True, applied
    unavailable = {item["key"]: item for item in applied["unavailable"]}
    assert "debuggers.dut.executable" in unavailable
    assert "openocd" in unavailable["debuggers.dut.executable"]["reason"]
    after = document_of(path)
    assert after["debuggers"]["dut"]["executable"] is None
    assert after["debuggers"]["dut"]["type"] == "openocd", "adoption never changes which program drives the board"
    # The probe serial is not a backend question and still lands.
    assert after["debuggers"]["dut"]["probe_id"] == PROBE_SERIAL


# ---------------------------------------------------------------------------
# The grants, and the one door.


def test_without_the_description_grant_the_agent_gets_the_values_and_not_the_write(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A refusal that still removes the transcription.

    The grant belongs to the operator and this call does not argue with it. What
    it does is hand back the exact keys and values rather than a probe listing
    somebody has to correlate by hand — which is the whole complaint in #76,
    answered even where the write is shut."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch)
    before = path.read_text(encoding="utf-8")
    attached(monkeypatch)
    tools = service(workspace)
    try:
        refused = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert refused["ok"] is False
    assert refused["error_type"] == "permission_denied"
    assert refused["permission"] == CONFIG_DESCRIPTION_RIGHT
    assert refused["applied"] is False
    assert {item["key"]: item["value"] for item in refused["carried"]}["debuggers.dut.probe_id"] == PROBE_SERIAL
    assert refused["write"]["tool"] == PROJECT_CONFIG_SET
    assert path.read_text(encoding="utf-8") == before


def test_nothing_is_read_or_written_while_this_server_holds_hardware(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Refused one step earlier than a plain write, because this touches the board.

    Enumerating probes and connecting in HOTPLUG mode talks to hardware a run may
    be holding, so the refusal comes before discovery rather than before the
    write."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    before = path.read_text(encoding="utf-8")
    reached: dict[str, bool] = {}

    def discover(timeout_s: float = 10.0, *, probe_id: str | None = None) -> dict:  # pragma: no cover - must not run
        reached["discovery"] = True
        return {"ok": True}

    monkeypatch.setattr("agentic_hil.adopt.discover_attached_hardware", discover)
    tools = service(workspace)
    try:
        started = tools.call("bench_run_start", {"devices": [{"kind": "debugger", "id": "dut"}], "label": "held"})
        assert started["ok"] is True, started
        refused = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
        assert tools.call("bench_run_stop")["ok"] is True
    finally:
        tools.close()

    assert refused["ok"] is False
    assert refused["error_type"] == "config_write_in_open_run"
    assert refused["retry_safe"] is True
    assert "discovery" not in reached
    assert path.read_text(encoding="utf-8") == before


def test_the_plan_is_a_pure_reading_of_a_document(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """No document, no plan: with nothing configured there is no entry to fill.

    The planner is the part a reviewer has to be able to reason about on its own,
    so it takes a document and a discovery result and returns a decision — no
    file, no permissions, no way to reach either."""
    plan = plan_adoption({"debuggers": {}}, {"ok": True, "backend": "stlink", "probe_id": PROBE_SERIAL})
    assert plan["ok"] is False
    assert plan["field"] == "debugger_id"


def test_an_unknown_debugger_name_is_refused_rather_than_created(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A probe entry is not something this brings into existence.

    A `debuggers` entry decides which backend drives a board and with which
    scripts; created from a name in a call it would be an OpenOCD entry nobody
    asked for. Filling one in is this path's job, adding one is not."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    attached(monkeypatch)
    tools = service(workspace)
    try:
        refused = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True, "debugger_id": "second_board"})
    finally:
        tools.close()

    assert refused["ok"] is False
    assert refused["error_type"] == "unknown_device"
    assert refused["configured_debuggers"] == ["dut"]
    assert "second_board" not in document_of(path)["debuggers"]


def test_the_operator_path_still_cannot_move_a_permission(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The CLI waives the description grant and nothing else.

    The before/after comparison inside the write path reads the document rather
    than the request, and it is not conditional on who is asking. This checks it
    from the outside: an operator run leaves every permission exactly as it was,
    including in the entry it creates."""
    workspace, path = placeholder_bench(tmp_path, monkeypatch)
    attached(monkeypatch)
    before = granted(document_of(path))

    result = adopt_hardware()

    assert result["ok"] is True, result
    after = granted(document_of(path))
    assert not [key for key in before if before[key] != after[key]]
    assert after["com_ports.dut_uart.permissions.allow_write"] is False
    assert after[f"permissions.{CONFIG_DESCRIPTION_RIGHT}"] is False
    assert after[f"permissions.{CONFIG_PERMISSIONS_RIGHT}"] is False


def test_the_cli_dry_run_writes_nothing(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    workspace, path = placeholder_bench(tmp_path, monkeypatch)
    attached(monkeypatch)
    before = path.read_text(encoding="utf-8")

    result = adopt_hardware(dry_run=True)

    assert result["ok"] is True, result
    assert result["applied"] is False
    assert len(result["carried"]) == 4
    assert path.read_text(encoding="utf-8") == before


def test_the_write_goes_through_the_one_door(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Every change this path makes is a project_config_set change.

    Not a stylistic point: the grants, the schema check on each value, the
    validate-before-replace and the provenance record all live there, and a
    second way to write this file would have to reimplement every one of them."""
    workspace, _ = placeholder_bench(tmp_path, monkeypatch, **{CONFIG_DESCRIPTION_RIGHT: True})
    attached(monkeypatch)
    seen: list[dict] = []
    real = project_config_adopt_hardware.__globals__["project_config_set"]

    def recording(*args: Any, **kwargs: Any) -> dict:
        seen.append({"changes": args[2], "actor": kwargs.get("actor"), "via": kwargs.get("via")})
        return real(*args, **kwargs)

    monkeypatch.setattr("agentic_hil.adopt.project_config_set", recording)
    tools = service(workspace)
    try:
        applied = tools.call(PROJECT_CONFIG_ADOPT, {"apply": True})
    finally:
        tools.close()

    assert applied["ok"] is True, applied
    assert len(seen) == 1
    assert seen[0]["actor"] == "agent"
    assert seen[0]["via"] == f"mcp:{PROJECT_CONFIG_ADOPT}"
    assert all(sorted(change) == ["key", "value"] for change in seen[0]["changes"])
