"""Keep the hash-pinned lock files under requirements/ what their inputs say.

Every lock file records, on its second line, the exact ``uv pip compile``
command that produced it. This tool reads those commands back and runs them, so
a lock is only ever written by the resolver and the options that wrote it:
``--universal`` keeps every platform's markers, ``--generate-hashes`` keeps the
hashes, and the whole set is resolved against its input at once, so no pin can
move past a ceiling another package sets.

Updating the files any other way does not work, and has been tried. Dependabot
moved pins one at a time and, where it re-resolved a file, resolved it for one
interpreter on one platform: pylink-square went to 2.0.1 in a lock whose pyocd
requires it below 2.0, the markers that carry colorama, pywin32-ctypes and
hidapi to Windows and macOS were dropped, and every hash-pinned install in CI
failed with ResolutionImpossible. The refresh workflow runs this tool instead,
and CI runs ``--check`` on every pull request so that a lock which no longer
follows from its input is caught by name rather than by thirteen installs.

Three modes:

    python tools/refresh_locks.py
        Refresh. Every exact pin in a .in file moves to its newest release,
        then every lock is recompiled with --upgrade.

    python tools/refresh_locks.py --check
        Verify. Every lock is recompiled without --upgrade and the tree is
        left as it was; a lock that came out different fails the run with
        the pins that moved.

    python tools/refresh_locks.py --uv-requirement
        Print uv's own hash-pinned lines from requirements/container.txt, so
        the workflows install the resolver with --require-hashes like
        everything else they install.

``--summary PATH`` writes what a refresh changed as one Markdown table, which
is the body of the pull request that carries it.
"""

from __future__ import annotations

import argparse
import re
import shlex
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

REQUIREMENTS = "requirements"
CONTAINER_LOCK = "container.txt"
HEADER = "# This file was autogenerated by uv via the following command:"
# A pin at the start of a line, in a lock or in an input. The version ends at
# the first space, backslash or semicolon, whichever the file uses next: a lock
# continues with ` \` before its hashes, an input may carry a marker.
PIN = re.compile(r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)==(?P<version>[^\s\\;]+)", re.MULTILINE)
# An exact pin an input file holds on its own: no extras, no marker, nothing
# after the version but whitespace. `tomli>=2; python_version < "3.11"` is a
# floor and stays where the maintainer put it; `uv==0.12.13` is what moves.
EXACT_PIN = re.compile(r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)==(?P<version>[^\s\\;\[]+)[ \t]*(?=\r?$)", re.MULTILINE)

# The options of a recorded command that take a value, so the one positional
# argument, the file the command compiles, can be told from them.
VALUED_OPTIONS = frozenset({"-o", "--output-file", "--python-version", "--extra", "-p", "--python", "-c", "--constraint"})

Runner = Callable[[list[str], str | None, Path], str]


class LockError(Exception):
    """A lock or an input this tool cannot work from, with the reason."""


@dataclass(frozen=True)
class Change:
    file: str
    name: str
    before: str | None
    after: str | None


def run_uv(command: list[str], stdin: str | None, cwd: Path) -> str:
    """Run one uv command from the repository root and return its stdout.

    uv's own stderr is the decisive line when it refuses, so it is kept whole.
    """
    completed = subprocess.run(command, input=stdin, cwd=cwd, capture_output=True, text=True, encoding="utf-8")
    if completed.returncode != 0:
        raise LockError(f"{shlex.join(command)} failed with exit status {completed.returncode}:\n{completed.stderr.rstrip()}")
    return completed.stdout


def lock_files(root: Path) -> list[Path]:
    return sorted((root / REQUIREMENTS).glob("*.txt"))


def recorded_command(root: Path, lock: Path) -> list[str]:
    """The command on the lock's second line, checked to be the one that wrote it."""
    relative = lock.relative_to(root).as_posix()
    lines = lock.read_text(encoding="utf-8").splitlines()
    if len(lines) < 2 or lines[0] != HEADER or not lines[1].startswith("#"):
        raise LockError(f"{relative} does not start with the uv header that records how it was compiled")
    command = shlex.split(lines[1].lstrip("#").strip())
    if command[:3] != ["uv", "pip", "compile"]:
        raise LockError(f"{relative} records {shlex.join(command)}, which is not a uv pip compile command")
    output = option_value(command, "-o", "--output-file")
    if output != relative:
        raise LockError(f"{relative} records a command that writes {output!r}, not itself")
    return command


def option_value(command: list[str], *names: str) -> str | None:
    for index, argument in enumerate(command):
        if argument in names and index + 1 < len(command):
            return command[index + 1]
        for name in names:
            if argument.startswith(f"{name}="):
                return argument.split("=", 1)[1]
    return None


def input_of(command: list[str]) -> str:
    """The one positional argument of the recorded command: the file it compiles."""
    positional = []
    skip = False
    for argument in command[3:]:
        if skip:
            skip = False
            continue
        if argument in VALUED_OPTIONS:
            skip = True
            continue
        if argument.startswith("-"):
            continue
        positional.append(argument)
    if len(positional) != 1:
        raise LockError(f"{shlex.join(command)} compiles {len(positional)} inputs; this tool reads exactly one")
    return positional[0]


def canonical(name: str) -> str:
    """The one spelling of a project name, as the index and uv both write it."""
    return re.sub(r"[-_.]+", "-", name).lower()


def pins(text: str) -> dict[str, str]:
    """Every `name==version` at the start of a line, by canonical name."""
    return {canonical(match.group("name")): match.group("version") for match in PIN.finditer(text)}


def pin_changes(file: str, before: str, after: str) -> list[Change]:
    old, new = pins(before), pins(after)
    changes = []
    for name in sorted(old.keys() | new.keys()):
        if old.get(name) != new.get(name):
            changes.append(Change(file, name, old.get(name), new.get(name)))
    return changes


def newest_releases(root: Path, names: list[str], python_version: str | None, run: Runner) -> dict[str, str]:
    """What the index serves as the newest release of each name, resolved by uv.

    `--no-deps` asks for the names alone, so a package whose newest release
    would not resolve together with the rest is still reported, and the lock
    compile that follows is where that is decided.
    """
    if not names:
        return {}
    command = ["uv", "pip", "compile", "--no-deps", "--no-header", "--no-annotate", "--upgrade", "--quiet"]
    if python_version:
        command += ["--python-version", python_version]
    command.append("-")
    return pins(run(command, "\n".join(names) + "\n", root))


def bump_exact_pins(root: Path, run: Runner) -> list[Change]:
    """Move every exact pin in the input files to its newest release.

    Only the inputs that a lock records as its own are read, and only bare
    `name==version` lines move. The floors stay: they mirror pyproject.toml,
    and the lock compile is what moves what sits above them.
    """
    changes = []
    for lock in lock_files(root):
        command = recorded_command(root, lock)
        source = input_of(command)
        if not source.endswith(".in"):
            continue
        path = root / source
        text = path.read_bytes().decode("utf-8")
        exact = {match.group("name"): match.group("version") for match in EXACT_PIN.finditer(text)}
        if not exact:
            continue
        newest = newest_releases(root, sorted(exact), option_value(command, "--python-version"), run)
        for name, version in exact.items():
            new = newest.get(canonical(name))
            if new is None or new == version:
                continue
            text = re.sub(rf"^{re.escape(name)}=={re.escape(version)}[ \t]*(?=\r?$)", f"{name}=={new}", text, count=1, flags=re.MULTILINE)
            changes.append(Change(source, canonical(name), version, new))
        path.write_bytes(text.encode("utf-8"))
    return changes


def recompile(root: Path, lock: Path, run: Runner, upgrade: bool) -> list[Change]:
    """Run the lock's recorded command in place and report which pins moved."""
    command = recorded_command(root, lock)
    if upgrade:
        command.append("--upgrade")
    before = lock.read_bytes().decode("utf-8")
    run(command, None, root)
    after = lock.read_bytes().decode("utf-8")
    return pin_changes(lock.relative_to(root).as_posix(), before, after)


def check(root: Path, run: Runner) -> list[str]:
    """Recompile every lock without upgrading; report the ones that changed.

    The tree is left as it was found, whatever the result, so the check can be
    run in a working copy without touching it.
    """
    problems = []
    for lock in lock_files(root):
        original = lock.read_bytes()
        try:
            changes = recompile(root, lock, run, upgrade=False)
            drifted = original != lock.read_bytes()
        finally:
            lock.write_bytes(original)
        if not drifted:
            continue
        relative = lock.relative_to(root).as_posix()
        moved = ", ".join(f"{change.name} {change.before or 'absent'} to {change.after or 'absent'}" for change in changes)
        problems.append(f"{relative} does not follow from its input: recompiling it moves {moved or 'no pin, but the file changed'}")
    if problems:
        problems.append("Regenerate with the command on the lock's second line, or refresh every lock with: python tools/refresh_locks.py")
    return problems


def refresh(root: Path, run: Runner) -> list[Change]:
    changes = bump_exact_pins(root, run)
    for lock in lock_files(root):
        changes.extend(recompile(root, lock, run, upgrade=True))
    return changes


def summary(changes: list[Change]) -> str:
    """The refresh as one Markdown table, by file and then by name."""
    if not changes:
        return "Every lock was already current.\n"
    rows = ["| Package | File | From | To |", "| --- | --- | --- | --- |"]
    for change in sorted(changes, key=lambda change: (change.file, change.name)):
        rows.append(f"| {change.name} | {change.file} | {change.before or 'absent'} | {change.after or 'absent'} |")
    return (
        "Every lock file under `requirements/` recompiled with the `uv pip compile` command recorded on its second line, "
        "with `--upgrade`, after each exact pin in the `.in` inputs moved to its newest release.\n\n"
        + "\n".join(rows)
        + "\n"
    )


def uv_requirement(root: Path) -> str:
    """uv's own block of requirements/container.txt: its pin and its hashes.

    uv depends on nothing, so that block alone is a complete requirements file
    pip accepts with --require-hashes. The container lock is where uv is pinned
    on purpose, and installing the resolver from it means a refresh is made by
    the uv release the image's own tests have run.
    """
    text = (root / REQUIREMENTS / CONTAINER_LOCK).read_text(encoding="utf-8")
    block = re.search(r"^uv==.*?(?=^\S|\Z)", text, flags=re.MULTILINE | re.DOTALL)
    if block is None:
        raise LockError(f"{REQUIREMENTS}/{CONTAINER_LOCK} pins no uv")
    lines = [line for line in block.group(0).splitlines() if not line.lstrip().startswith("#")]
    if not any("--hash=sha256:" in line for line in lines):
        raise LockError(f"{REQUIREMENTS}/{CONTAINER_LOCK} pins uv without a hash")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None, run: Runner = run_uv) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="recompile without upgrading and fail if any lock changes")
    mode.add_argument("--uv-requirement", action="store_true", help="print uv's hash-pinned lines from the container lock")
    parser.add_argument("--summary", type=Path, help="write what the refresh changed to this Markdown file")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1], help=argparse.SUPPRESS)
    arguments = parser.parse_args(argv)
    root = arguments.root.resolve()
    try:
        if arguments.uv_requirement:
            sys.stdout.write(uv_requirement(root))
            return 0
        if arguments.check:
            problems = check(root, run)
            for problem in problems:
                print(problem, file=sys.stderr)
            return 1 if problems else 0
        changes = refresh(root, run)
        text = summary(changes)
        if arguments.summary:
            arguments.summary.write_text(text, encoding="utf-8")
        sys.stdout.write(text)
        return 0
    except LockError as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
