"""One process owns one physical CAN bus; named participants share it.

CAN is a shared medium, and a ``can_buses`` entry has always modelled it as a
device with a single owner: ``can:<adapter>:<channel>`` is one exclusive,
machine-wide lock, so two runs on one bench serialise against each other even
when they are talking to two different devices on the same wire. This module is
the other half of that model, and it changes nothing about the first: a bus entry
with no ``shares:`` is still the single-owner bus it was, no broker is started
for it, and nothing here is on its path.

**The broker holds the same lock everybody else would have held.** It takes
``can:<adapter>:<channel>`` through the ordinary :class:`~agentic_hil.bench.BenchMutex`
and holds it for its whole life, so every exclusivity the single-owner model
enforced keeps being enforced — by one process, exactly once — and a single-owner
run on the same bench is refused by the bus being busy, as before. Participants
take *logical* locks ``<bus-key>#<name>``, so two runs may not share one
participant name while any number of distinctly named participants proceed in
parallel.

**Attaching proves the peer owns the bus, rather than asking it.** A broker's
claim to hold the lock is worth nothing on its own — a stale endpoint or an
impostor listener says the same words. So the attaching participant probes the
lock itself: it reads the holder record, checks that the pid there is the pid the
peer announced, and then *tries to take the bus lock*. Success is the refusal:
a lock this process could take is a lock the peer does not hold.

**Two staleness contracts, because they fail differently.** The protocol carries
a version and a digest of its own message surface, so a client and a broker from
different releases refuse each other at attach instead of misparsing frames
mid-run. The connection counter is the other one: it starts at the surface
revision, increments on every attach, and is published in the descriptor, so a
client attaching on a descriptor that has since moved on is refused cleanly with
both numbers named rather than acting on a picture of the bus that is out of
date.

**Local IPC only.** ``AF_UNIX`` on POSIX, a named pipe on Windows, never a
network listener. The HMAC authkey handshake in ``multiprocessing.connection``
runs before anything is unpickled, so an unauthenticated peer never reaches the
message loop. The key itself is generated by the broker, written beside the
descriptor with owner-only permissions, and deliberately kept out of every
structure this module builds: it is in no result, no report and no log line, and
``redact.redact_sensitive`` carries an ``authkey`` arm as the second line of that
defense rather than the first.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import secrets
import socket
import stat
import subprocess
import sys
import tempfile
import threading
import time
from contextlib import suppress
from dataclasses import dataclass, field
from multiprocessing.connection import AuthenticationError, Client, Connection, Listener
from pathlib import Path

# `_LifetimeLock` is reached for by name on purpose. The probe below has to take
# the bus lock and put it straight back without leaving a holder record behind —
# a probe that recorded itself as an owner would be read by the next contender as
# one — and `BenchMutex` maintains exactly that record.
from agentic_hil.bench import (
    BenchMutex,
    DeviceBusyError,
    _LifetimeLock,
    fold_resource_name,
    resource_digest,
    utc_now_iso,
)
from agentic_hil.config import (
    ConfigError,
    atomic_write_text,
    display_path,
    load_authoritative_config,
    safe_append_text,
    safe_directory,
    safe_read_text,
)
from agentic_hil.devices import DeviceError, can_device
from agentic_hil.process import spawn_detached_process
from agentic_hil.report import logs_directory, safe_filename, timestamp_for_filename
from agentic_hil.types import AgenticHILConfig, CanBusConfig, CanShareConfig, JsonObject

# Bumped whenever a message name, a field name or the meaning of a field moves.
# It seeds the connection counter, so a client built against another revision
# cannot present a counter a broker of this one would accept even by accident.
SURFACE_REVISION = 1
PROTOCOL_VERSION = 1

# The message surface itself, as data. The digest below is taken over it, so a
# field added, removed or renamed here changes what a cross-release peer is
# compared against — the digest cannot drift from the surface it describes,
# because it is computed from it rather than maintained beside it.
MESSAGE_SURFACE: dict[str, tuple[str, ...]] = {
    "attach": ("protocol_version", "protocol_digest", "expected_counter", "bus_key", "participant", "requires_listen_only", "client_pid"),
    "attached": ("ok", "counter", "broker_pid", "bus_key", "participant", "view", "bus_frame_log", "listen_only", "listen_only_enforcement", "listen_only_proof", "attached_participants"),
    "detach": (),
    "detached": ("ok", "participant", "attached_participants"),
    "send": ("frame",),
    "sent": ("ok", "frame_seq", "participant", "frame", "frames_used", "max_frames"),
    "read": ("max_frames", "wait_timeout_s"),
    "frames": ("ok", "frames", "frames_read", "frames_used", "max_frames"),
    "incident": ("scope", "reason", "detail"),
    "incident_recorded": ("ok", "scope", "reason", "bus_gated", "aborted_participants"),
    "poll_incident": (),
    "status": (),
    "bus_status": ("ok", "bus_key", "counter", "broker_pid", "attached_participants", "bus_gated", "frames_seen"),
    "frame": ("id", "extended", "rtr", "data_hex"),
    "abort": ("scope", "reason", "detail", "recovery_action", "at"),
}
PROTOCOL_DIGEST = hashlib.sha256(json.dumps(MESSAGE_SURFACE, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()[:16]

BROKER_DIRECTORY_NAME = "can-brokers"
DESCRIPTOR_VERSION = 1
AUTHKEY_BYTES = 32
# How long a client waits for a broker it started to publish its descriptor, and
# how long a broker that nobody attached to waits before deciding it was started
# for a client that has since died. The second is what keeps a failed attach from
# leaving a process on the bus lock.
BROKER_START_TIMEOUT_S = 30.0
BROKER_FIRST_ATTACH_TIMEOUT_S = 30.0
BROKER_POLL_INTERVAL_S = 0.05
# A counter mismatch is the ordinary outcome of two runs attaching at once, so a
# client re-reads and retries rather than failing the run; it is bounded because
# a retry loop against a broker that keeps moving is livelock wearing a retry.
ATTACH_COUNTER_RETRIES = 8
CLIENT_REQUEST_TIMEOUT_S = 30.0

BROKER_EXIT_OK = 0
BROKER_EXIT_BUS_BUSY = 3
BROKER_EXIT_ADAPTER = 4
BROKER_EXIT_CONFIG = 5


# ---------------------------------------------------------------------------
# Names, addresses and the rendezvous on disk.


def bus_lock_key(config: AgenticHILConfig, bus_id: str) -> str:
    """The machine-wide lock a broker for this bus takes, spelled as the device spells it."""
    return can_device(config, bus_id).lock_key


def participant_lock_key(bus_key: str, participant: str) -> str:
    """The logical lock one named participant takes: ``<bus-key>#<name>``.

    Folded through the same rule as the bus key, so a participant cannot be
    split from itself by spelling."""
    return fold_resource_name(f"{bus_key}#{participant}")


def _broker_home(lock_root: Path) -> Path:
    """Where a broker publishes itself: beside the device locks it holds.

    Derived from the lock root rather than from the home directory again, so a
    broker and the lock it takes cannot end up in two different places — which is
    the split ``bench.device_lock_root`` exists to prevent for locks."""
    return safe_directory(lock_root.parent / BROKER_DIRECTORY_NAME)


def descriptor_path(bus_key: str, lock_root: Path) -> Path:
    return _broker_home(lock_root) / f"{resource_digest(bus_key)}.broker.json"


def authkey_path(bus_key: str, lock_root: Path) -> Path:
    return _broker_home(lock_root) / f"{resource_digest(bus_key)}.authkey"


def broker_log_path(bus_key: str, lock_root: Path) -> Path:
    return _broker_home(lock_root) / f"{resource_digest(bus_key)}.broker.log"


def endpoint_family() -> str:
    return "AF_PIPE" if os.name == "nt" else "AF_UNIX"


def endpoint_address(bus_key: str, lock_root: Path) -> str:
    """The local IPC address for this bus, on this lock root.

    Deliberately *not* under the lock root on POSIX. An ``AF_UNIX`` path is
    capped near 108 bytes by the kernel, and the lock root follows the user's
    home — under a test sandbox or a long profile name a socket there simply
    cannot be bound, and the failure would arrive as a truncated path rather than
    as anything readable. The address is published in the descriptor, so it does
    not have to be derivable by anyone; it only has to be short, per user, and
    distinct per lock root, which is what the tag is."""
    tag = hashlib.sha256(f"{os.path.normcase(str(lock_root))}\0{bus_key}".encode()).hexdigest()[:20]
    if os.name == "nt":
        return rf"\\.\pipe\agentic-hil-can-{tag}"
    directory = Path(tempfile.gettempdir()) / f"agentic-hil-can-{os.getuid()}"
    directory.mkdir(mode=0o700, exist_ok=True)
    entry = os.stat(directory)
    if entry.st_uid != os.getuid() or not stat.S_ISDIR(entry.st_mode):
        raise ConfigError("config_invalid", "The CAN broker socket directory is not owned by this user.", {"path": str(directory)})
    os.chmod(directory, 0o700)
    return str(directory / f"{tag}.sock")


@dataclass(frozen=True)
class BrokerDescriptor:
    """What a running broker publishes about itself.

    Carries no authkey, by construction: this record is JSON on disk and is
    copied into refusals, and the one thing that must never be in a JSON
    structure is the key. The key lives in a sibling file with owner-only
    permissions and is read as bytes."""

    bus_key: str
    endpoint: str
    family: str
    pid: int
    protocol_version: int
    protocol_digest: str
    counter: int
    started_at: str

    def as_json(self) -> JsonObject:
        return {
            "version": DESCRIPTOR_VERSION,
            "bus_key": self.bus_key,
            "endpoint": self.endpoint,
            "family": self.family,
            "pid": self.pid,
            "protocol_version": self.protocol_version,
            "protocol_digest": self.protocol_digest,
            "counter": self.counter,
            "started_at": self.started_at,
        }

    @staticmethod
    def from_json(value: object) -> BrokerDescriptor | None:
        if not isinstance(value, dict) or value.get("version") != DESCRIPTOR_VERSION:
            return None
        try:
            return BrokerDescriptor(
                bus_key=str(value["bus_key"]),
                endpoint=str(value["endpoint"]),
                family=str(value["family"]),
                pid=int(value["pid"]),
                protocol_version=int(value["protocol_version"]),
                protocol_digest=str(value["protocol_digest"]),
                counter=int(value["counter"]),
                started_at=str(value["started_at"]),
            )
        except (KeyError, TypeError, ValueError):
            return None


def read_descriptor(bus_key: str, lock_root: Path) -> BrokerDescriptor | None:
    try:
        text = safe_read_text(descriptor_path(bus_key, lock_root))
    except (FileNotFoundError, OSError, UnicodeDecodeError, ConfigError):
        return None
    try:
        return BrokerDescriptor.from_json(json.loads(text))
    except ValueError:
        return None


def _remove_stale_broker(bus_key: str, lock_root: Path) -> None:
    """Clear the rendezvous of a broker that is provably not on the bus.

    Only ever called after a lock probe has shown the bus lock free, which is the
    one state a live broker cannot be in: it holds that lock from before it
    publishes until after it unpublishes. The authkey goes with the descriptor
    because a key without an endpoint authenticates nothing."""
    for path in (descriptor_path(bus_key, lock_root), authkey_path(bus_key, lock_root)):
        with suppress(FileNotFoundError, OSError):
            os.unlink(path)


def _write_authkey(path: Path, key: bytes) -> None:
    """Write the HMAC key owner-only, replacing whatever was there.

    ``os.open`` with an explicit mode rather than a text write, because the mode
    has to be on the file from the moment it exists — a chmod afterwards is a
    window. On Windows the mode bits are advisory; what protects the file there
    is that it lives under the user's own profile, the same argument the device
    locks beside it rest on."""
    with suppress(FileNotFoundError):
        os.unlink(path)
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_BINARY", 0), 0o600)
    try:
        os.write(descriptor, key)
    finally:
        os.close(descriptor)


def _read_authkey(path: Path) -> bytes | None:
    try:
        with open(path, "rb") as handle:
            key = handle.read(AUTHKEY_BYTES * 2)
    except OSError:
        return None
    return key or None


# ---------------------------------------------------------------------------
# The lock probe: the peer holds the bus, or it does not.


def probe_bus_lock(bus_key: str, expected_pid: int, lock_root: Path) -> JsonObject:
    """Whether the process at ``expected_pid`` really holds this bus lock.

    Three questions, and the third is the one that cannot be faked. The holder
    record must exist and name that pid on this host — but the record is
    advisory, so an impostor could have written it. The lock itself is not: a
    lock this process can take is a lock nobody holds. So the probe *tries to
    acquire* the bus lock non-blocking, and treats success as the refusal.

    Nothing is written on the way through. A successful probe acquisition is
    released immediately and never leaves a holder record, so a probe cannot be
    mistaken for an owner by the next contender."""
    record_path = lock_root / f"{resource_digest(bus_key)}.holder.json"
    record: JsonObject | None = None
    try:
        record = json.loads(safe_read_text(record_path))
    except (FileNotFoundError, OSError, UnicodeDecodeError, ConfigError, ValueError):
        record = None
    owner = record.get("owner") if isinstance(record, dict) and isinstance(record.get("owner"), dict) else None
    probe = _LifetimeLock(lock_root / f"{resource_digest(bus_key)}.lock")
    try:
        probe.acquire()
    except (BlockingIOError, OSError):
        held = True
    else:
        held = False
        with suppress(BaseException):
            probe.release()
    if not held:
        return {
            "ok": False,
            "error_type": "can_broker_not_bus_owner",
            "summary": "The CAN broker endpoint does not hold this bus lock; the bus lock was free while it claimed to own the bus.",
            "bus_key": bus_key,
            "claimed_broker_pid": expected_pid,
            "bus_lock_held": False,
            "retry_safe": False,
            "side_effect_committed": False,
        }
    if owner is None or record is None or record.get("state") != "held":
        return {
            "ok": False,
            "error_type": "can_broker_not_bus_owner",
            "summary": "The CAN bus lock is held, but no holder record identifies the process holding it as the broker that answered.",
            "bus_key": bus_key,
            "claimed_broker_pid": expected_pid,
            "bus_lock_held": True,
            "retry_safe": True,
            "side_effect_committed": False,
        }
    if owner.get("pid") != expected_pid or owner.get("host") != socket.gethostname():
        return {
            "ok": False,
            "error_type": "can_broker_not_bus_owner",
            "summary": "The CAN bus lock is held by a different process than the endpoint that answered.",
            "bus_key": bus_key,
            "claimed_broker_pid": expected_pid,
            "bus_lock_holder": {"pid": owner.get("pid"), "host": owner.get("host")},
            "bus_lock_held": True,
            "retry_safe": False,
            "side_effect_committed": False,
        }
    return {"ok": True, "bus_key": bus_key, "broker_pid": expected_pid, "bus_lock_held": True}


# ---------------------------------------------------------------------------
# Frames on the wire.


def frame_to_wire(frame_id: int, data: bytes, *, extended: bool = False, rtr: bool = False) -> JsonObject:
    return {"id": int(frame_id), "extended": bool(extended), "rtr": bool(rtr), "data_hex": bytes(data).hex()}


def wire_frame_valid(value: object) -> bool:
    if not isinstance(value, dict) or set(value) != set(MESSAGE_SURFACE["frame"]):
        return False
    if not isinstance(value.get("id"), int) or isinstance(value.get("id"), bool):
        return False
    if not isinstance(value.get("extended"), bool) or not isinstance(value.get("rtr"), bool):
        return False
    data_hex = value.get("data_hex")
    if not isinstance(data_hex, str):
        return False
    try:
        bytes.fromhex(data_hex)
    except ValueError:
        return False
    maximum = 0x1FFFFFFF if value["extended"] else 0x7FF
    return 0 <= value["id"] <= maximum


def filter_accepts(share: CanShareConfig, frame_id: int) -> bool:
    """Whether a participant's view carries this identifier. No filter is every identifier."""
    if not share.filters:
        return True
    return any((frame_id & term.mask) == (term.identifier & term.mask) for term in share.filters)


def share_view(share: CanShareConfig) -> JsonObject:
    return {
        "filter": [{"id": term.identifier, "mask": term.mask, "extended": term.extended} for term in share.filters],
        "max_frames": share.max_frames,
        "requires_listen_only": share.requires_listen_only,
        "permissions": {"allow_read": share.permissions.allow_read, "allow_write": share.permissions.allow_write},
    }


def listen_only_proof(bus_config: CanBusConfig) -> str:
    """What a listen-only claim on this bus is, in one word.

    ``service`` enforcement is the broker declining to forward, which is software
    filtering and is named as such here and everywhere it is reported. It is
    never rendered as the controller proof, whatever the adapter is capable of:
    the point of the configuration key is that the two are not interchangeable."""
    return "controller" if bus_config.listen_only_enforcement == "controller" else "software_filter"


# ---------------------------------------------------------------------------
# The broker.


@dataclass
class _Attached:
    name: str
    share: CanShareConfig
    connection: Connection
    client_pid: int
    attached_at: str
    frames_used: int = 0
    queue: list[JsonObject] = field(default_factory=list)
    abort: JsonObject | None = None


class CanBroker:
    """One process, one physical bus, many named participants.

    Owns the bus lock and the adapter for its whole life. Everything a
    participant does to the medium passes through here, which is what makes the
    whole-bus frame log complete: the broker is the only writer, so a frame in a
    participant's own log is a frame in this one, under the same sequence
    number."""

    def __init__(self, config: AgenticHILConfig, bus_id: str, *, mutex: BenchMutex | None = None):
        self.config = config
        self.bus_id = bus_id
        self.bus_config = config.can_buses[bus_id]
        self.mutex = mutex or BenchMutex(frontend="can-broker", label=f"can-broker:{bus_id}")
        self.bus_key = bus_lock_key(config, bus_id)
        self.lock_root = self.mutex.root
        self.counter = SURFACE_REVISION
        self.attach_total = 0
        self.frame_seq = 0
        self.bus_gated = False
        self.bus_incident: JsonObject | None = None
        self.participants: dict[str, _Attached] = {}
        self.adapter_session: object | None = None
        self.bus_frame_log = ""
        self._guard = threading.RLock()
        self._stopping = threading.Event()
        self._listener: Listener | None = None
        self._authkey = secrets.token_bytes(AUTHKEY_BYTES)
        self._endpoint = ""
        self._started_at = utc_now_iso()

    # -- lifecycle ---------------------------------------------------------

    def take_bus(self) -> None:
        """Hold the machine-wide bus lock for this broker's whole life."""
        self.mutex.acquire_named(self.bus_key)

    def open_bus(self) -> JsonObject:
        from agentic_hil.can import open_adapter

        self.bus_frame_log = str(Path(logs_directory(self.config)) / f"can-bus-{timestamp_for_filename()}-{safe_filename(self.bus_id, 'bus')}.jsonl")
        safe_append_text(self.bus_frame_log, "")
        opened = open_adapter(self.config, self.bus_id, self.bus_config, False)
        if not opened.get("ok"):
            return {key: value for key, value in opened.items() if key != "session"}
        self.adapter_session = opened["session"]
        self._log_bus({"event": "broker_start", "bus_id": self.bus_id, "bus_key": self.bus_key, "adapter": self.bus_config.adapter, "channel": self.bus_config.channel, "listen_only": self.bus_config.listen_only, "listen_only_enforcement": self.bus_config.listen_only_enforcement, "listen_only_proof": listen_only_proof(self.bus_config), "broker_pid": os.getpid()})
        return {"ok": True}

    def publish(self) -> None:
        self._endpoint = endpoint_address(self.bus_key, self.lock_root)
        if os.name != "nt":
            # The bus lock is already ours, so no other broker for this bus can
            # exist and a socket file here is the corpse of one the OS reaped.
            with suppress(FileNotFoundError):
                os.unlink(self._endpoint)
        self._listener = Listener(self._endpoint, endpoint_family(), authkey=self._authkey)
        _write_authkey(authkey_path(self.bus_key, self.lock_root), self._authkey)
        self._write_descriptor()

    def _write_descriptor(self) -> None:
        descriptor = BrokerDescriptor(
            bus_key=self.bus_key,
            endpoint=self._endpoint,
            family=endpoint_family(),
            pid=os.getpid(),
            protocol_version=PROTOCOL_VERSION,
            protocol_digest=PROTOCOL_DIGEST,
            counter=self.counter,
            started_at=self._started_at,
        )
        atomic_write_text(descriptor_path(self.bus_key, self.lock_root), json.dumps(descriptor.as_json(), indent=2) + "\n")

    def serve(self, first_attach_timeout_s: float = BROKER_FIRST_ATTACH_TIMEOUT_S) -> int:
        """Accept participants until the last one detaches.

        The first-attach deadline is not tidiness: a client that spawned a broker
        and then died before attaching would otherwise leave a process sitting on
        the bus lock with nobody able to say why, which is exactly the orphan the
        automatic lifecycle exists to avoid."""
        assert self._listener is not None
        deadline = time.monotonic() + first_attach_timeout_s
        handlers: list[threading.Thread] = []
        waiter = threading.Thread(target=self._first_attach_watchdog, args=(deadline,), daemon=True)
        waiter.start()
        while not self._stopping.is_set():
            try:
                connection = self._listener.accept()
            except (AuthenticationError, OSError):
                continue
            except BaseException:
                break
            if self._stopping.is_set():
                with suppress(BaseException):
                    connection.close()
                break
            handler = threading.Thread(target=self._serve_connection, args=(connection,), daemon=True)
            handler.start()
            handlers.append(handler)
            handlers = [item for item in handlers if item.is_alive()]
        for handler in handlers:
            handler.join(timeout=5.0)
        return BROKER_EXIT_OK

    def _first_attach_watchdog(self, deadline: float) -> None:
        while not self._stopping.is_set() and time.monotonic() < deadline:
            with self._guard:
                if self.attach_total:
                    return
            time.sleep(BROKER_POLL_INTERVAL_S)
        with self._guard:
            if self.attach_total:
                return
        self.stop("no_participant_attached")

    def stop(self, reason: str) -> None:
        if self._stopping.is_set():
            return
        self._stopping.set()
        self._log_bus({"event": "broker_stop", "bus_id": self.bus_id, "reason": reason, "frames_seen": self.frame_seq})
        # `accept()` is blocked in the serve loop; a throwaway connection is what
        # wakes it, and it is authenticated like any other so the wake cannot come
        # from outside.
        with suppress(BaseException):
            Client(self._endpoint, endpoint_family(), authkey=self._authkey).close()

    def shutdown(self) -> None:
        with suppress(BaseException):
            if self._listener is not None:
                self._listener.close()
        session = self.adapter_session
        if session is not None:
            with suppress(BaseException):
                session.close()  # type: ignore[attr-defined]
            self.adapter_session = None
        for path in (descriptor_path(self.bus_key, self.lock_root), authkey_path(self.bus_key, self.lock_root)):
            with suppress(FileNotFoundError, OSError):
                os.unlink(path)
        if os.name != "nt" and self._endpoint:
            with suppress(FileNotFoundError, OSError):
                os.unlink(self._endpoint)
        with suppress(BaseException):
            self.mutex.release_all()

    # -- connections -------------------------------------------------------

    def _serve_connection(self, connection: Connection) -> None:
        attached: _Attached | None = None
        try:
            while True:
                try:
                    message = connection.recv()
                except (EOFError, OSError):
                    break
                if not isinstance(message, dict):
                    self._reply(connection, {"ok": False, "error_type": "can_broker_invalid_message", "summary": "The CAN broker received a message it cannot read."})
                    break
                kind = message.get("message")
                if attached is None:
                    if kind != "attach":
                        self._reply(connection, {"ok": False, "error_type": "can_broker_not_attached", "summary": "The first CAN broker message must be an attach."})
                        break
                    reply, attached = self._handle_attach(message, connection)
                    self._reply(connection, reply)
                    if attached is None:
                        break
                    continue
                if kind == "detach":
                    self._reply(connection, self._handle_detach(attached))
                    attached = None
                    break
                self._reply(connection, self._handle_request(attached, kind, message))
        finally:
            with suppress(BaseException):
                connection.close()
            if attached is not None:
                # A participant whose process died without detaching must not keep
                # the bus. The connection closing is the detach.
                self._detach(attached, "connection_closed")

    def _reply(self, connection: Connection, payload: JsonObject) -> None:
        with suppress(OSError, EOFError):
            connection.send(payload)

    # -- attach ------------------------------------------------------------

    def _handle_attach(self, message: JsonObject, connection: Connection) -> tuple[JsonObject, _Attached | None]:
        with self._guard:
            if message.get("protocol_version") != PROTOCOL_VERSION or message.get("protocol_digest") != PROTOCOL_DIGEST:
                return {
                    "ok": False,
                    "error_type": "can_broker_protocol_mismatch",
                    "summary": "The CAN broker and this client were built from different releases of the broker protocol.",
                    "broker_protocol_version": PROTOCOL_VERSION,
                    "client_protocol_version": message.get("protocol_version"),
                    "broker_protocol_digest": PROTOCOL_DIGEST,
                    "client_protocol_digest": message.get("protocol_digest"),
                    "retry_safe": False,
                    "side_effect_committed": False,
                }, None
            if message.get("expected_counter") != self.counter:
                return {
                    "ok": False,
                    "error_type": "can_broker_counter_mismatch",
                    "summary": "The CAN broker connection counter has moved on since this client read the broker descriptor.",
                    "broker_counter": self.counter,
                    "client_counter": message.get("expected_counter"),
                    "retry_safe": True,
                    "side_effect_committed": False,
                }, None
            if message.get("bus_key") != self.bus_key:
                return {"ok": False, "error_type": "can_broker_wrong_bus", "summary": "The CAN broker endpoint owns a different bus than the client asked for.", "broker_bus_key": self.bus_key, "client_bus_key": message.get("bus_key"), "retry_safe": False, "side_effect_committed": False}, None
            if self.bus_gated:
                return {"ok": False, "error_type": "can_bus_gated", "summary": "The CAN bus is gated by a bus-scoped incident and accepts no further participants.", "bus_key": self.bus_key, "incident": self.bus_incident, "retry_safe": False, "side_effect_committed": False}, None
            name = message.get("participant")
            if not isinstance(name, str) or name not in self.bus_config.shares:
                return {"ok": False, "error_type": "can_participant_not_configured", "summary": "The authoritative config declares no such participant view on this CAN bus.", "bus_id": self.bus_id, "participant": name, "configured_participants": sorted(self.bus_config.shares), "retry_safe": False, "side_effect_committed": False}, None
            if name in self.participants:
                return {"ok": False, "error_type": "can_participant_busy", "summary": "A participant of that name is already attached to this CAN bus.", "bus_key": self.bus_key, "participant": name, "retry_safe": True, "side_effect_committed": False}, None
            share = self.bus_config.shares[name]
            conflict = self._listen_only_conflict(name, share)
            if conflict is not None:
                return conflict, None
            self.counter += 1
            self.attach_total += 1
            attached = _Attached(name=name, share=share, connection=connection, client_pid=int(message.get("client_pid") or 0), attached_at=utc_now_iso())
            self.participants[name] = attached
            with suppress(ConfigError, OSError):
                self._write_descriptor()
            self._log_bus({"event": "participant_attach", "bus_id": self.bus_id, "participant": name, "counter": self.counter, "client_pid": attached.client_pid, "view": share_view(share)})
            return {
                "ok": True,
                "message": "attached",
                "counter": self.counter,
                "broker_pid": os.getpid(),
                "bus_key": self.bus_key,
                "bus_id": self.bus_id,
                "participant": name,
                "view": share_view(share),
                "bus_frame_log": display_path(self.config, self.bus_frame_log),
                "listen_only": self.bus_config.listen_only,
                "listen_only_enforcement": self.bus_config.listen_only_enforcement,
                "listen_only_proof": listen_only_proof(self.bus_config),
                "attached_participants": sorted(self.participants),
            }, attached

    def _listen_only_conflict(self, name: str, share: CanShareConfig) -> JsonObject | None:
        """Listen-only is a property of the bus, so the two kinds cannot coexist.

        The flag stands for a controller-level proof, and a controller has one
        state for the whole medium — not one per acceptance filter. So a
        participant that needs the bus silent and a participant that transmits
        are refused against each other rather than both being seated and one of
        them being quietly wrong. The enforcement level is named in the refusal
        because it is what the refusal is worth: at ``service`` the guarantee
        would have been software filtering, and saying so is the point of the
        key."""
        common = {
            "error_type": "can_listen_only_conflict",
            "bus_id": self.bus_id,
            "bus_key": self.bus_key,
            "participant": name,
            "listen_only": self.bus_config.listen_only,
            "listen_only_enforcement": self.bus_config.listen_only_enforcement,
            "listen_only_proof": listen_only_proof(self.bus_config),
            "retry_safe": False,
            "side_effect_committed": False,
            "ok": False,
        }
        if share.permissions.allow_write and self.bus_config.listen_only:
            return {**common, "summary": "This CAN bus is configured listen_only, so a participant that may transmit cannot attach to it.", "conflicting_participants": []}
        writers = sorted(other for other, item in self.participants.items() if item.share.permissions.allow_write)
        listeners = sorted(other for other, item in self.participants.items() if item.share.requires_listen_only)
        if share.requires_listen_only and writers:
            return {**common, "summary": "A participant that requires a listen-only bus cannot attach while a transmitting participant is attached.", "conflicting_participants": writers}
        if share.permissions.allow_write and listeners:
            return {**common, "summary": "A transmitting participant cannot attach while a participant that requires a listen-only bus is attached.", "conflicting_participants": listeners}
        return None

    # -- detach ------------------------------------------------------------

    def _handle_detach(self, attached: _Attached) -> JsonObject:
        self._detach(attached, "requested")
        with self._guard:
            return {"ok": True, "message": "detached", "participant": attached.name, "attached_participants": sorted(self.participants)}

    def _detach(self, attached: _Attached, reason: str) -> None:
        stop = False
        with self._guard:
            if self.participants.get(attached.name) is attached:
                self.participants.pop(attached.name, None)
                self._log_bus({"event": "participant_detach", "bus_id": self.bus_id, "participant": attached.name, "reason": reason, "frames_used": attached.frames_used})
            stop = not self.participants and self.attach_total > 0
        if stop:
            self.stop("last_participant_detached")

    # -- requests ----------------------------------------------------------

    def _handle_request(self, attached: _Attached, kind: object, message: JsonObject) -> JsonObject:
        if kind == "status":
            with self._guard:
                return {"ok": True, "message": "bus_status", "bus_key": self.bus_key, "counter": self.counter, "broker_pid": os.getpid(), "attached_participants": sorted(self.participants), "bus_gated": self.bus_gated, "frames_seen": self.frame_seq}
        if kind == "incident":
            return self._handle_incident(attached, message)
        if kind == "poll_incident":
            with self._guard:
                return {"ok": True, "message": "incident_poll", "aborted": attached.abort is not None, "abort": attached.abort}
        blocked = self._blocked(attached)
        if blocked is not None:
            return blocked
        if kind == "send":
            return self._handle_send(attached, message)
        if kind == "read":
            return self._handle_read(attached, message)
        return {"ok": False, "error_type": "can_broker_invalid_message", "summary": "The CAN broker received a message it cannot read.", "message": kind}

    def _blocked(self, attached: _Attached) -> JsonObject | None:
        with self._guard:
            if attached.abort is None:
                return None
            scope = attached.abort.get("scope")
            return {
                "ok": False,
                "error_type": "can_bus_incident" if scope == "bus" else "can_participant_incident",
                "summary": "This CAN participant's run was aborted by a bus-scoped incident." if scope == "bus" else "This CAN participant's run was aborted by a participant-scoped incident.",
                "bus_id": self.bus_id,
                "participant": attached.name,
                "abort": attached.abort,
                "bus_gated": self.bus_gated,
                "retry_safe": False,
                "side_effect_committed": False,
            }

    def _handle_incident(self, attached: _Attached, message: JsonObject) -> JsonObject:
        scope = message.get("scope")
        if scope not in {"bus", "participant"}:
            return {"ok": False, "error_type": "invalid_argument", "summary": "A CAN incident scope must be 'bus' or 'participant'.", "scope": scope}
        reason = str(message.get("reason") or "unspecified")
        abort = {
            "scope": scope,
            "reason": reason,
            "detail": message.get("detail"),
            "recovery_action": self.config.recovery.auto_recover,
            "at": utc_now_iso(),
        }
        with self._guard:
            if scope == "bus":
                self.bus_gated = True
                self.bus_incident = abort
                for participant in self.participants.values():
                    participant.abort = abort
                aborted = sorted(self.participants)
            else:
                attached.abort = abort
                aborted = [attached.name]
            self._log_bus({"event": "incident", "bus_id": self.bus_id, "scope": scope, "reason": reason, "reported_by": attached.name, "aborted_participants": aborted, "bus_gated": self.bus_gated})
            return {"ok": True, "message": "incident_recorded", "scope": scope, "reason": reason, "bus_gated": self.bus_gated, "aborted_participants": aborted, "abort": abort}

    def _handle_send(self, attached: _Attached, message: JsonObject) -> JsonObject:
        from agentic_hil.can import CanFrame

        if not attached.share.permissions.allow_write:
            return {"ok": False, "error_type": "permission_denied", "summary": "Writing this CAN bus is disabled for this participant by the authoritative config.", "bus_id": self.bus_id, "participant": attached.name, "retry_safe": False, "side_effect_committed": False}
        wire = message.get("frame")
        if not wire_frame_valid(wire):
            return {"ok": False, "error_type": "invalid_argument", "summary": "The CAN broker received a frame it cannot read.", "participant": attached.name, "side_effect_committed": False}
        assert isinstance(wire, dict)
        if not filter_accepts(attached.share, int(wire["id"])):
            return {"ok": False, "error_type": "can_participant_filter_violation", "summary": "This CAN participant's view does not carry that identifier, so it may not send it.", "bus_id": self.bus_id, "participant": attached.name, "frame": wire, "view": share_view(attached.share), "retry_safe": False, "side_effect_committed": False}
        budget = self._spend_budget(attached)
        if budget is not None:
            return budget
        frame = CanFrame(id=int(wire["id"]), extended=bool(wire["extended"]), rtr=bool(wire["rtr"]), data=bytes.fromhex(str(wire["data_hex"])))
        try:
            sent = self.adapter_session.send(frame)  # type: ignore[union-attr]
        except BaseException as error:
            # The adapter itself raised: that is the bus, not this participant.
            return self._raise_bus_incident("can_adapter_send_raised", f"{type(error).__name__}: {error}")
        with self._guard:
            self.frame_seq += 1
            seq = self.frame_seq
            self._log_bus({"event": "frame", "seq": seq, "direction": "tx", "bus_id": self.bus_id, "participant": attached.name, "frame": wire, "ok": bool(sent.get("ok"))})
        if not sent.get("ok"):
            return {"ok": False, "error_type": "can_send_failed", "summary": str(sent.get("summary", "The CAN adapter failed to send a frame.")), "bus_id": self.bus_id, "participant": attached.name, "frame_seq": seq, "frame": wire, "backend_error": sent.get("backend_error"), "side_effect_status": "unknown"}
        return {"ok": True, "message": "sent", "frame_seq": seq, "participant": attached.name, "frame": wire, "frames_used": attached.frames_used, "max_frames": attached.share.max_frames}

    def _handle_read(self, attached: _Attached, message: JsonObject) -> JsonObject:
        if not attached.share.permissions.allow_read:
            return {"ok": False, "error_type": "permission_denied", "summary": "Reading this CAN bus is disabled for this participant by the authoritative config.", "bus_id": self.bus_id, "participant": attached.name, "retry_safe": False, "side_effect_committed": False}
        try:
            max_frames = int(message.get("max_frames") or 1)
            wait_timeout_s = float(message.get("wait_timeout_s") or 0.0)
        except (TypeError, ValueError):
            return {"ok": False, "error_type": "invalid_argument", "summary": "max_frames must be an integer and wait_timeout_s a number.", "participant": attached.name}
        if max_frames < 1 or max_frames > self.bus_config.max_buffer_frames:
            return {"ok": False, "error_type": "invalid_argument", "summary": "max_frames must be between 1 and the bus max_buffer_frames.", "max_buffer_frames": self.bus_config.max_buffer_frames, "participant": attached.name}
        with self._guard:
            pending = len(attached.queue)
        if pending < max_frames:
            drawn = self._draw_from_bus(min(self.bus_config.max_buffer_frames, max(max_frames, 1)), max(0.0, min(wait_timeout_s, self.bus_config.timeout_s, 60.0)))
            if drawn is not None:
                return drawn
        with self._guard:
            taken = attached.queue[:max_frames]
            del attached.queue[: len(taken)]
            attached.frames_used += len(taken)
            over = attached.frames_used > attached.share.max_frames
        if over:
            return self._budget_exhausted(attached)
        return {"ok": True, "message": "frames", "frames": taken, "frames_read": len(taken), "frames_used": attached.frames_used, "max_frames": attached.share.max_frames, "participant": attached.name}

    def _draw_from_bus(self, max_frames: int, wait_timeout_s: float) -> JsonObject | None:
        """Read the medium once and fan the frames out to every view that carries them.

        The broker is the only reader of the adapter, which is what makes the
        whole-bus log complete and what stops two participants from consuming
        each other's traffic: a read is destructive at the controller, so a
        per-participant read would have been one participant stealing frames."""
        from agentic_hil.can import normalize_received_frames

        try:
            read = self.adapter_session.read(max_frames, wait_timeout_s)  # type: ignore[union-attr]
        except BaseException as error:
            return self._raise_bus_incident("can_adapter_read_raised", f"{type(error).__name__}: {error}")
        if not read.get("ok"):
            return self._raise_bus_incident("can_adapter_read_failed", str(read.get("summary", "The CAN adapter failed to read.")))
        frames = normalize_received_frames(read.get("frames", []))
        if frames is None:
            return self._raise_bus_incident("can_adapter_invalid_response", "The CAN adapter returned malformed frame data.")
        with self._guard:
            for frame in frames:
                self.frame_seq += 1
                seq = self.frame_seq
                wire = {"id": int(frame["id"]), "extended": bool(frame["extended"]), "rtr": bool(frame["rtr"]), "data_hex": str(frame["data_hex"])}
                delivered = sorted(name for name, item in self.participants.items() if item.share.permissions.allow_read and filter_accepts(item.share, wire["id"]))
                self._log_bus({"event": "frame", "seq": seq, "direction": "rx", "bus_id": self.bus_id, "frame": wire, "delivered_to": delivered})
                for name in delivered:
                    self.participants[name].queue.append({**wire, "frame_seq": seq})
        return None

    def _spend_budget(self, attached: _Attached) -> JsonObject | None:
        with self._guard:
            if attached.frames_used >= attached.share.max_frames:
                return self._budget_exhausted(attached)
            attached.frames_used += 1
        return None

    def _budget_exhausted(self, attached: _Attached) -> JsonObject:
        abort = {"scope": "participant", "reason": "can_participant_frame_budget_exhausted", "detail": {"max_frames": attached.share.max_frames}, "recovery_action": self.config.recovery.auto_recover, "at": utc_now_iso()}
        with self._guard:
            attached.abort = abort
            self._log_bus({"event": "incident", "bus_id": self.bus_id, "scope": "participant", "reason": abort["reason"], "reported_by": attached.name, "aborted_participants": [attached.name], "bus_gated": self.bus_gated})
        return {"ok": False, "error_type": "can_participant_frame_budget_exhausted", "summary": "This CAN participant used its whole configured frame budget; its run is aborted and the bus keeps running.", "bus_id": self.bus_id, "participant": attached.name, "frames_used": attached.frames_used, "max_frames": attached.share.max_frames, "abort": abort, "retry_safe": False, "side_effect_committed": False}

    def _raise_bus_incident(self, reason: str, detail: object) -> JsonObject:
        abort = {"scope": "bus", "reason": reason, "detail": detail, "recovery_action": self.config.recovery.auto_recover, "at": utc_now_iso()}
        with self._guard:
            self.bus_gated = True
            self.bus_incident = abort
            for participant in self.participants.values():
                participant.abort = abort
            aborted = sorted(self.participants)
            self._log_bus({"event": "incident", "bus_id": self.bus_id, "scope": "bus", "reason": reason, "reported_by": "broker", "aborted_participants": aborted, "bus_gated": True})
        return {"ok": False, "error_type": "can_bus_incident", "summary": "A physical CAN bus incident aborted every participant's run and gated the bus.", "bus_id": self.bus_id, "abort": abort, "aborted_participants": aborted, "bus_gated": True, "retry_safe": False, "side_effect_committed": False}

    def _log_bus(self, event: JsonObject) -> None:
        if not self.bus_frame_log:
            return
        with suppress(ConfigError, OSError, ValueError):
            safe_append_text(self.bus_frame_log, json.dumps({"at": utc_now_iso(), **event}) + "\n")


# ---------------------------------------------------------------------------
# The participant side.


class ParticipantError(RuntimeError):
    """An attach that was refused, carrying the refusal a caller reports."""

    def __init__(self, result: JsonObject):
        super().__init__(str(result.get("summary", "CAN participant attach was refused.")))
        self.result = result


class Participant:
    """One run's named connection to a brokered bus.

    Keeps its own view of the traffic beside the broker's whole-bus log. Both
    carry the broker's frame sequence number, so a frame this participant sent is
    the same frame in the bus log — attributable from either end without either
    log having to be trusted about the other."""

    def __init__(self, config: AgenticHILConfig, bus_id: str, name: str, connection: Connection, attached: JsonObject, mutex: BenchMutex, lock_key: str, *, broker_process: subprocess.Popen | None = None):
        self.config = config
        self.bus_id = bus_id
        self.name = name
        self.connection = connection
        self.attached = attached
        self.mutex = mutex
        self.lock_key = lock_key
        self.broker_process = broker_process
        self.broker_pid = int(attached.get("broker_pid") or 0)
        self.counter = int(attached.get("counter") or 0)
        self.view = attached.get("view")
        self.bus_frame_log = attached.get("bus_frame_log")
        self.detached = False
        self.log_path = str(Path(logs_directory(config)) / f"can-participant-{timestamp_for_filename()}-{safe_filename(bus_id, 'bus')}-{safe_filename(name, 'participant')}.jsonl")
        with suppress(ConfigError, OSError):
            safe_append_text(self.log_path, "")
        self._log({"event": "attach", "bus_id": bus_id, "participant": name, "counter": self.counter, "broker_pid": self.broker_pid, "bus_frame_log": self.bus_frame_log, "view": self.view, "listen_only": attached.get("listen_only"), "listen_only_enforcement": attached.get("listen_only_enforcement"), "listen_only_proof": attached.get("listen_only_proof")})

    # -- operations --------------------------------------------------------

    def send(self, frame_id: int, data: bytes, *, extended: bool = False, rtr: bool = False) -> JsonObject:
        wire = frame_to_wire(frame_id, data, extended=extended, rtr=rtr)
        result = self._request({"message": "send", "frame": wire})
        self._log({"event": "frame", "direction": "tx", "participant": self.name, "frame_seq": result.get("frame_seq"), "frame": wire, "ok": bool(result.get("ok"))})
        return result

    def read(self, max_frames: int = 1, wait_timeout_s: float = 0.0) -> JsonObject:
        result = self._request({"message": "read", "max_frames": max_frames, "wait_timeout_s": wait_timeout_s})
        for frame in result.get("frames", []) if isinstance(result.get("frames"), list) else []:
            self._log({"event": "frame", "direction": "rx", "participant": self.name, "frame_seq": frame.get("frame_seq"), "frame": {key: value for key, value in frame.items() if key != "frame_seq"}, "ok": True})
        return result

    def report_incident(self, scope: str, reason: str, detail: object = None) -> JsonObject:
        result = self._request({"message": "incident", "scope": scope, "reason": reason, "detail": detail})
        self._log({"event": "incident", "scope": scope, "reason": reason, "participant": self.name, "bus_gated": result.get("bus_gated")})
        return result

    def poll_incident(self) -> JsonObject:
        return self._request({"message": "poll_incident"})

    def status(self) -> JsonObject:
        return self._request({"message": "status"})

    def detach(self) -> JsonObject:
        if self.detached:
            return {"ok": True, "message": "detached", "participant": self.name, "already_detached": True}
        self.detached = True
        result: JsonObject = {"ok": True, "message": "detached", "participant": self.name}
        try:
            result = self._request({"message": "detach"})
        except (OSError, EOFError, ParticipantError):
            result = {"ok": True, "message": "detached", "participant": self.name, "broker_unreachable": True}
        finally:
            with suppress(BaseException):
                self.connection.close()
            self._log({"event": "detach", "participant": self.name, "attached_participants": result.get("attached_participants")})
            with suppress(BaseException):
                self.mutex.release_all()
        return result

    def __enter__(self) -> Participant:
        return self

    def __exit__(self, *_: object) -> None:
        self.detach()

    # -- plumbing ----------------------------------------------------------

    def _request(self, payload: JsonObject) -> JsonObject:
        self.connection.send(payload)
        if not self.connection.poll(CLIENT_REQUEST_TIMEOUT_S):
            raise ParticipantError({"ok": False, "error_type": "can_broker_timeout", "summary": "The CAN broker did not answer within the request timeout.", "bus_id": self.bus_id, "participant": self.name, "side_effect_status": "unknown"})
        answer = self.connection.recv()
        if not isinstance(answer, dict):
            raise ParticipantError({"ok": False, "error_type": "can_broker_invalid_message", "summary": "The CAN broker answered with a message this client cannot read.", "bus_id": self.bus_id, "participant": self.name})
        return answer

    def _log(self, event: JsonObject) -> None:
        with suppress(ConfigError, OSError, ValueError):
            safe_append_text(self.log_path, json.dumps({"at": utc_now_iso(), **event}) + "\n")


def attach_participant(
    config: AgenticHILConfig,
    bus_id: str,
    participant: str,
    *,
    mutex: BenchMutex | None = None,
    wait_s: float = 0.0,
    start_timeout_s: float = BROKER_START_TIMEOUT_S,
    allow_start: bool = True,
) -> Participant:
    """Attach this run to a named participant view, starting the broker if needed.

    Order matters and is the point. The participant lock is taken *first*, so a
    second run claiming the same name is refused by the ordinary bench mutex
    before any broker is spoken to and whether or not one is running. Then the
    broker is found or started, and only then is the peer believed — after the
    lock probe says it is the process holding the bus."""
    bus_config = config.can_buses.get(bus_id)
    if bus_config is None:
        raise ParticipantError({"ok": False, "error_type": "can_bus_not_configured", "summary": "CAN bus is not available in the authoritative config.", "bus_id": bus_id, "configured_buses": sorted(config.can_buses)})
    if not bus_config.shares:
        raise ParticipantError({"ok": False, "error_type": "can_bus_not_shared", "summary": "This CAN bus declares no shares:, so it is a single-owner bus and has no participants.", "bus_id": bus_id})
    if participant not in bus_config.shares:
        raise ParticipantError({"ok": False, "error_type": "can_participant_not_configured", "summary": "The authoritative config declares no such participant view on this CAN bus.", "bus_id": bus_id, "participant": participant, "configured_participants": sorted(bus_config.shares)})
    try:
        bus_key = bus_lock_key(config, bus_id)
    except DeviceError as error:
        raise ParticipantError(error.result) from error
    owner = mutex or BenchMutex(frontend="can-participant", label=f"can-participant:{bus_id}#{participant}")
    lock_key = participant_lock_key(bus_key, participant)
    try:
        owner.acquire_named(lock_key, wait_s=wait_s)
    except DeviceBusyError as error:
        raise ParticipantError({**error.result, "bus_id": bus_id, "participant": participant, "participant_lock": lock_key, "summary": f"CAN participant '{participant}' on bus '{bus_id}' is already held by another run; two runs may not share one participant name."}) from error
    try:
        return _attach_with_broker(config, bus_id, participant, bus_key, owner, lock_key, start_timeout_s, allow_start)
    except BaseException:
        with suppress(BaseException):
            owner.release_all()
        raise


def _attach_with_broker(config: AgenticHILConfig, bus_id: str, participant: str, bus_key: str, owner: BenchMutex, lock_key: str, start_timeout_s: float, allow_start: bool) -> Participant:
    lock_root = owner.root
    deadline = time.monotonic() + start_timeout_s
    started: subprocess.Popen | None = None
    last: JsonObject = {"ok": False, "error_type": "can_broker_unavailable", "summary": "No CAN broker for this bus could be reached or started.", "bus_id": bus_id, "bus_key": bus_key}
    attempts = 0
    while time.monotonic() < deadline:
        descriptor = read_descriptor(bus_key, lock_root)
        if descriptor is not None:
            attempts += 1
            outcome = _attach_once(config, bus_id, participant, bus_key, descriptor, owner, lock_key, lock_root, started)
            if isinstance(outcome, Participant):
                return outcome
            last = outcome
            if outcome.get("error_type") == "can_broker_counter_mismatch" and attempts <= ATTACH_COUNTER_RETRIES:
                time.sleep(BROKER_POLL_INTERVAL_S)
                continue
            if allow_start and outcome.get("error_type") == "can_broker_not_bus_owner" and outcome.get("bus_lock_held") is False:
                # A descriptor whose bus lock is free is a broker that was killed
                # before it could clean up after itself: `shutdown` removes the
                # descriptor *before* releasing the lock, so the two states can
                # only be seen together when nothing ran the cleanup at all.
                #
                # Refusing here would let one hard-killed broker brick the bus
                # until somebody deleted a file by hand. Removing the corpse is
                # safe precisely because the probe already failed: the endpoint
                # behind it owns nothing, so nothing is taken from anybody — and
                # an impostor's planted descriptor gets the same treatment,
                # having never been spoken to. When starting a broker is not
                # allowed there is nothing to replace it with, so the refusal
                # stands and the caller is told the peer is not the bus owner.
                _remove_stale_broker(bus_key, lock_root)
                continue
            if outcome.get("retry_safe") is not True:
                raise ParticipantError(outcome)
            time.sleep(BROKER_POLL_INTERVAL_S)
            continue
        if not allow_start:
            raise ParticipantError({**last, "error_type": "can_broker_unavailable", "summary": "No CAN broker is running for this bus and starting one was not allowed."})
        if started is None or started.poll() is not None:
            if started is not None and started.poll() == BROKER_EXIT_BUS_BUSY:
                # Somebody else owns the physical bus: either the broker that won
                # the start race, whose descriptor is about to appear, or a
                # single-owner run, in which case the deadline is the refusal.
                started = None
                time.sleep(BROKER_POLL_INTERVAL_S)
                continue
            started = _spawn_broker(config, bus_id, bus_key, lock_root)
        time.sleep(BROKER_POLL_INTERVAL_S)
    if started is not None and started.poll() is None:
        with suppress(BaseException):
            started.terminate()
    raise ParticipantError(last)


def _attach_once(config: AgenticHILConfig, bus_id: str, participant: str, bus_key: str, descriptor: BrokerDescriptor, owner: BenchMutex, lock_key: str, lock_root: Path, started: subprocess.Popen | None) -> Participant | JsonObject:
    if descriptor.protocol_version != PROTOCOL_VERSION or descriptor.protocol_digest != PROTOCOL_DIGEST:
        return {
            "ok": False,
            "error_type": "can_broker_protocol_mismatch",
            "summary": "The CAN broker running for this bus was built from a different release of the broker protocol.",
            "bus_id": bus_id,
            "broker_protocol_version": descriptor.protocol_version,
            "client_protocol_version": PROTOCOL_VERSION,
            "broker_protocol_digest": descriptor.protocol_digest,
            "client_protocol_digest": PROTOCOL_DIGEST,
            "retry_safe": False,
            "side_effect_committed": False,
        }
    probe = probe_bus_lock(bus_key, descriptor.pid, lock_root)
    if not probe["ok"]:
        return {**probe, "bus_id": bus_id, "participant": participant}
    key = _read_authkey(authkey_path(bus_key, lock_root))
    if key is None:
        return {"ok": False, "error_type": "can_broker_unavailable", "summary": "The CAN broker published no authentication key beside its descriptor.", "bus_id": bus_id, "retry_safe": True, "side_effect_committed": False}
    try:
        connection = Client(descriptor.endpoint, descriptor.family, authkey=key)
    except AuthenticationError as error:
        return {"ok": False, "error_type": "can_broker_authentication_failed", "summary": "The CAN broker refused this client's authentication key.", "bus_id": bus_id, "backend_error": str(error), "retry_safe": False, "side_effect_committed": False}
    except (FileNotFoundError, ConnectionRefusedError, OSError) as error:
        return {"ok": False, "error_type": "can_broker_unavailable", "summary": "The CAN broker endpoint could not be reached.", "bus_id": bus_id, "backend_error": str(error), "retry_safe": True, "side_effect_committed": False}
    try:
        connection.send(
            {
                "message": "attach",
                "protocol_version": PROTOCOL_VERSION,
                "protocol_digest": PROTOCOL_DIGEST,
                "expected_counter": descriptor.counter,
                "bus_key": bus_key,
                "participant": participant,
                "requires_listen_only": config.can_buses[bus_id].shares[participant].requires_listen_only,
                "client_pid": os.getpid(),
            }
        )
        if not connection.poll(CLIENT_REQUEST_TIMEOUT_S):
            raise TimeoutError("The CAN broker did not answer the attach request.")
        answer = connection.recv()
    except BaseException as error:
        with suppress(BaseException):
            connection.close()
        return {"ok": False, "error_type": "can_broker_unavailable", "summary": "The CAN broker did not complete the attach handshake.", "bus_id": bus_id, "backend_error": f"{type(error).__name__}: {error}", "retry_safe": True, "side_effect_committed": False}
    if not isinstance(answer, dict) or not answer.get("ok"):
        with suppress(BaseException):
            connection.close()
        refusal = answer if isinstance(answer, dict) else {"ok": False, "error_type": "can_broker_invalid_message", "summary": "The CAN broker answered the attach with a message this client cannot read."}
        return {**refusal, "bus_id": bus_id, "participant": participant}
    return Participant(config, bus_id, participant, connection, answer, owner, lock_key, broker_process=started)


def _spawn_broker(config: AgenticHILConfig, bus_id: str, bus_key: str, lock_root: Path) -> subprocess.Popen:
    """Start a broker for this bus, detached from the run that started it.

    :func:`~agentic_hil.process.spawn_detached_process` rather than
    ``spawn_managed_process``, and the difference is the whole reason the broker
    is spawned through the detached name: a managed child joins a kill-on-close
    Job Object owned by this run, and a broker that died with whichever run
    happened to attach first would not be a shared bus — the second participant
    would lose the medium because the first one's run ended. The broker's
    lifetime is bounded by its own rules instead: the last participant
    detaching, and the first-attach deadline below.

    Losing the race for the bus lock is a clean exit, not an error — the
    winner's descriptor is what the loser's client then finds.

    The first-attach deadline travels on the command line rather than being read
    from this module in the child. A constant read in the child is a constant a
    caller cannot influence, and a test that sets it here would be quietly
    testing nothing."""
    # The child's diagnostics go to a file rather than to a pipe: nobody is left
    # reading a broker's stderr once the run that started it has moved on, and a
    # full pipe would block the broker mid-bus.
    with open(broker_log_path(bus_key, lock_root), "ab") as handle:
        return spawn_detached_process(
            [
                sys.executable,
                "-m",
                "agentic_hil.canbroker",
                "--workspace-root",
                str(config.work_dir),
                "--bus-id",
                bus_id,
                "--first-attach-timeout-s",
                str(BROKER_FIRST_ATTACH_TIMEOUT_S),
            ],
            stdin=subprocess.DEVNULL,
            stdout=handle,
            stderr=handle,
            cwd=str(config.work_dir),
        )


# ---------------------------------------------------------------------------
# The broker process entry point.


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="agentic-hil-can-broker", description="Own one physical CAN bus for its named participants.")
    parser.add_argument("--workspace-root", required=True)
    parser.add_argument("--bus-id", required=True)
    parser.add_argument("--first-attach-timeout-s", type=float, default=BROKER_FIRST_ATTACH_TIMEOUT_S)
    arguments = parser.parse_args(argv)
    try:
        config = load_authoritative_config(arguments.workspace_root)
    except ConfigError as error:
        print(json.dumps({"ok": False, "error_type": error.error_type, "summary": str(error)}), file=sys.stderr)
        return BROKER_EXIT_CONFIG
    bus_config = config.can_buses.get(arguments.bus_id)
    if bus_config is None or not bus_config.shares:
        print(json.dumps({"ok": False, "error_type": "can_bus_not_shared", "summary": "The authoritative config declares no shared CAN bus of that name.", "bus_id": arguments.bus_id}), file=sys.stderr)
        return BROKER_EXIT_CONFIG
    broker = CanBroker(config, arguments.bus_id)
    try:
        broker.take_bus()
    except DeviceBusyError as error:
        print(json.dumps({"ok": False, "error_type": "device_busy", "summary": str(error), "bus_key": broker.bus_key}), file=sys.stderr)
        return BROKER_EXIT_BUS_BUSY
    try:
        opened = broker.open_bus()
        if not opened.get("ok"):
            print(json.dumps(opened, default=str), file=sys.stderr)
            return BROKER_EXIT_ADAPTER
        broker.publish()
        return broker.serve(arguments.first_attach_timeout_s)
    finally:
        broker.shutdown()


if __name__ == "__main__":
    raise SystemExit(main())
